### ISSUE TITLE
限制 radius 大小

### ISSUE THREAD

**Issue by Yukaii** [Disfactory/Disfactory#100]
一次範圍太大 DB query 時間會爆久

https://github.com/Disfactory/Disfactory/blob/af2e6c83468a8cab7b0683164aac5ca50af5bdf7/backend/api/views/factories_cr.py#L41

前端的 query zoom 條件也需要一起限制，這張票給 Backend

**Comment by Yukaii** [comment]
可以測試的經緯度：[120.1, 23.234]

**Comment by Yukaii** [comment]
- [ ] 測試不同 range 下打 API 的 latency

**Comment by mhshih** [comment]
```
def benchmark(range):
    t1=time.time()
    url='https://middle2.disfactory.tw/api/factories?range='+range+'&lng=120.1&lat=23.234'
    resp=requests.get(url)
    t2=time.time()
    latency=t2-t1
    return latency
```

**Comment by stegben** [comment]
#116 已經讓大範圍的 query 加速許多了
