### ISSUE TITLE
20191211 雙指放大縮小會讓按鈕連帶放大縮小

### ISSUE THREAD

**Issue by Oriyar** [Disfactory/Disfactory#117]
**Describe this bug**
放大縮小時，會於比例尺約1/500有問題，按鍵鈕會共同放大縮小
**To Reproduce**
1. 打開頁面
2. 用兩指在「我要新增違章工廠」按鍵附近觸控縮放
3. 在比例尺約 1/500 時。所有按鈕和配置會跟著地圖放大縮小（包括我要新增違章工廠，+-，filter都會跟著變，然後 toolbar 會消失）

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: zen

**Additional context**

**Comment by Yukaii** [comment]
fixed in https://github.com/Disfactory/Disfactory/pull/118/commits/e0bfca0ad86eb1dc3d3b3a3f8b150461da28a108

**Comment by aelcenganda** [comment]
實測沒問題
