### ISSUE TITLE
按 Android 返回鍵會跳出，沒有返回上一頁

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#130]
**Describe the bug**
若使用者從 Messenger 或是 Line 打開連結，Android 使用者習慣用底下海苔條的返回鍵返回上一頁，但是會導致 disfactory 網頁被關閉。

**To Reproduce**
1. 用 Android 手機，從 Line、 Messenger、Facebook 打開 dev.disfactory.tw
2. 點擊「工廠圖標」
3. 點擊「補充資料」
3. 進入補充資料頁面後
4. 按 Android 功能列上的返回鍵
5. 離開網頁回到原應用程式

**Expected behavior**
回到上一頁，回到 disfactory 地圖首頁

**Smartphone (please complete the following information):**
zen phone 5Z | Messenger 版本243.0.0.12.117
OPPO R11s Plus | Android 7.1.1 | Chrome 79.0.3945.79

**Additional context**

**Comment by Yukaii** [comment]
push dummy state 進去 browser history

https://stackoverflow.com/questions/49954394/when-modal-popup-is-open-prevent-mobile-back-button-to-quit-the-site-close-t

**Comment by yoyo930021** [comment]
可以考慮上 vue-router 來處理？

**Comment by aelcenganda** [comment]
@yoyo930021 我今天測還沒 deploy 喔
