### ISSUE TITLE
Android 無法上傳照片

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#132]
**Describe the bug**
在新增工廠與修改資料的頁面，「新增照片」按鈕皆為灰色。按下去也無法新增照片

**To Reproduce**
1. 點擊「我要新增違章工廠」
2. 進入頁面，點擊「新增」照片
3. 無反應
4. 填妥其他資料
5. 仍可順利送出資料

**Expected behavior**
1. 「新增」照片按鈕為綠色
2. 能成功從手機新增照片，顯示在新增工廠頁面上
3. 若是沒有上傳照片，無法新增工廠。（送出按鈕 disable 或是跳出 error message）

**Screenshots**

![圖片](https://user-images.githubusercontent.com/9480974/70861301-ea860b80-1f66-11ea-953b-4fe3f8ed1e51.png)
![圖片](https://user-images.githubusercontent.com/9480974/70861307-f671cd80-1f66-11ea-8d72-f7350e76c8d6.png)

OPPO R11s Plus | Android 7.1.1Chrome 79.0.3945.79

**Comment by Yukaii** [comment]
related to #113 #123 修一個 iOS 壞一個 Android 😂 慘

**Comment by aelcenganda** [comment]
我剛剛用桌機測也慘慘慘，也無法上傳。

Device: 家用 PC
OS: Wins 10 家用版
Chrome: 64 位元版 79.0.3945.79

但有趣的是補充資訊那一頁是不讓點，出現


新增工廠是按下去沒反應
![圖片](https://user-images.githubusercontent.com/9480974/70864248-50848a00-1f8b-11ea-8c45-49bb9c6ad341.png)

**Comment by Yukaii** [comment]
補充資訊是還沒實作 😅 新增可能是上面改壞了
