### ISSUE TITLE
目前定位標示不清楚

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#135]
**Describe the bug**
在一般瀏覽地圖時顯示使用者「目前定位」的 icon 很不清楚，目前是藍框小圈圈，尤其是在有路名顯示的狀況下很難看出自己目前在哪裡。

**To Reproduce**

1.打開首頁
2. 點擊左方 toolbar 「目前定位」
3. 畫面跳至以目前定位為中心
4. 但老花眼的人很難看到

**Expected behavior**
要有老花眼的人可以看到自己目前定位在哪裡。
目前是藍框圈圈，建議可以變成上一版的實心藍點。

**Screenshots**
![圖片](https://user-images.githubusercontent.com/9480974/70861462-579aa080-1f69-11ea-91ed-a5351c619097.png)

**Smartphone (please complete the following information):**

OPPO R11s Plus | Android 7.1.1Chrome 79.0.3945.79

**Comment by Yukaii** [comment]
https://github.com/Disfactory/Disfactory/blob/e62d0eda104549092556bd4c7fdb3499141249e7/frontend/src/lib/map.ts#L417

從這邊幫 feature 上 style

```js
feature.setStyle(......)
```

**Comment by jenhaoyang** [comment]
我修改了map.ts後不知道該怎麼重新build專案，請問該怎麼做才能更新我的修改到網頁上呢(我都直接docker-compose up)

**Comment by Yukaii** [comment]
前端的部分第一次設定，先確定有安裝 nodejs 環境，進到專案根目錄，然後照以下操作：

```bash
cd frontend
npm i -g yarn
yarn # install dependencies
yarn serve # 跑起前端開發伺服器
```

跑起來的前端頁面會在 `http://localhost:8080` 看到

**Comment by Yukaii** [comment]
@jenhaoyang 如果這個步驟沒問題的話，也可以幫前端的 README 寫一份開發設定指南，並開個 PR 噢~

目前前端還沒有 Getting Started 部分的文件 😅

**Comment by jenhaoyang** [comment]
好的   我等等開一張票assign自己

**Comment by aelcenganda** [comment]
@jenhaoyang current location 圖標的部分， @yoyo930021 在 #182 會和使用者面向方位一起做掉。這個 Issue 你就先不用做了。

**Comment by jenhaoyang** [comment]
> 
> 
> @jenhaoyang current location 圖標的部分， @yoyo930021 在 #182 會和使用者面向方位一起做掉。這個 Issue 你就先不用做了。

OK

**Comment by aelcenganda** [comment]
#182 解決了
