### ISSUE TITLE
違章工廠 pin 不會隨著地圖放大縮小重新 query

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#136]
**Describe the bug**
地圖縮小後不會顯示其他地區的違章工廠，跨縣市會無法顯示另一個縣市的違章工廠。
若在台北市中心打開，縮到全台灣大小，只會顯示台南一帶的違章工廠。

**To Reproduce**
1. 打開首頁，定位到台北
2. 地圖顯示台北
2. 縮小地圖移動到外縣市，舉例來說，想要看彰化的違章工廠
3. 彰化地區未顯示任何違章工廠
4-1. 要試圖在台南附近新增違章工廠，進入用紅點選位置之後，才會顯示彰化附近的違章工廠。
4-2 或是在彰化地區放大到一定大小才看的到

**Expected behavior**
跨縣市瀏覽移到彰化時，可以看到彰化一帶的違章工廠。

**Screenshots**

從台北市縮小時看不到周圍的違章工廠 
![圖片](https://user-images.githubusercontent.com/9480974/70861620-b19c6580-1f6b-11ea-872c-d85b713a795a.png)

從嘉義縮小到全台灣時，看不到全台灣都有違章工廠分布
![圖片](https://user-images.githubusercontent.com/9480974/70861612-a9dcc100-1f6b-11ea-9d4a-8f8086e13300.png)

縮小地圖要再看到該地區的違章工廠，必須要進入新增違章工廠的頁面
![圖片](https://user-images.githubusercontent.com/9480974/70861637-e1e40400-1f6b-11ea-9d5b-1db3aa072720.png)

**Smartphone (please complete the following information):**
Device: iPhone SE
OS: iOS 13.1.2
Browser Chrome 78.0.3904.84

OPPO R11s Plus | Android 7.1.1Chrome 79.0.3945.79
**Additional context**

**Comment by Yukaii** [comment]
https://stackoverflow.com/questions/26734512/open-layers-3-zoom-map-event-handler

監聽 `change:resolution event`

**Comment by aelcenganda** [comment]
無法顯示是因為台北超過緯度 25，會在 #99 解決

**Comment by aelcenganda** [comment]
#99 解決，剩下的是要不要隨著地圖縮放，顯示 cluster 違章工廠，需要另開 issue
