### ISSUE TITLE
UI: 新增違章工廠時，使用者不知道如何更改選擇地點或跳出

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#137]
**Describe the bug**

1. 在不小心點到「新增工廠」按鈕進入選擇地點時，誤按的人不知道如何離開。
2. 在新增工廠過程中，尚未正式送出前，卻想要更改選擇的地點時，使用者不知道如何修改已經選擇的地點。

**To Reproduce**
1) 無法離開選擇地點頁面
1. 打開首頁
2. 點選「我要新增違章工廠」
3. 進入選擇地點頁面
4. 使用者不想要新增工廠，想要離開此頁面
5. 唯一的方法是先隨便選一個地點，進到新增工廠編輯頁面後不送出就按左上返回鍵離開
![圖片](https://user-images.githubusercontent.com/9480974/70861876-2a50f100-1f6f-11ea-9b8f-65d0912074d3.png)

2) 不知道如何修改已經選擇的地點
1. 打開首頁
2. 點選「我要新增違章工廠」
3. 進入選擇地點頁面
4. 點選「選擇地點」按鈕
5. 進入新增工廠編輯頁面
6. 使用者找不到可以變更選擇地點的方法
（其實只要再點選一次小地圖就可以變更選擇地點）
![圖片](https://user-images.githubusercontent.com/9480974/70861884-4b194680-1f6f-11ea-90b9-65ba29bd6edf.png)

**Expected behavior**
1) 在選擇地點頁面有離開按鈕
2) 在新增工廠頁面有更明確提示怎麼變更已選擇地點

**Smartphone (please complete the following information):**
- Device: iPhone SE
- OS: iOS 13.1.2
- Browser Chrome 78.0.3904.84

**Additional context**

**Comment by Yukaii** [comment]
related to #127
