### ISSUE TITLE
UI: 選擇地點時想要顯示比例尺和座標

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#139]
使用者測試時，表達希望：

1. 選擇地點時地圖有比例尺：
方便可以確認與自己的距離多少，方便放地圖圖標

2. 顯示座標或可輸入座標
因為不相信這個網頁的定位，想要用其他應用程式確認座標定位後再填入，或至少可獲得座標與其他應用程式定位座標比對。
（是台北人，所以不確定在地人會不會想要這個功能，要再做確認）

**Comment by yoyo930021** [comment]
1. 我會補上一個地圖用的比例尺
2. 是可以顯示座標 不過感覺這需求比較 Geek 點的感覺

**Comment by aelcenganda** [comment]
感謝加上比例尺！座標之後再說，我先關
