### ISSUE TITLE
補充資料確認送出之後，未更新到地圖顯示資料上

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#140]
**Describe the bug**
使用者無法確定自己是否有成功補充資料。

1. 補充資料，單項按確認後，沒有 success message 表示新增完成（有些使用者會試圖尋找「送出」按鈕，但找不到）。導致使用者會按從 navigation bar 返回，但是看不到自己新增的資訊。
2. 補宗資料除了工廠名稱更動以外，圖片、新增其他資訊的欄位，不會更新顯示在地圖上。

related to #133 

**To Reproduce**
1. 點擊工廠圖標
2. 點擊「補充資料」按鈕
3. 進入補充資料頁面
4. 編輯「新增其他資訊」
5. 按「確認」
6. **除了按鈕變成淺綠色以外，沒反應**
7. 按「返回」
8. 再次點擊工廠圖標和「補充資料」按鈕
9. 進入補充資料頁面，並未看見自己新增的「新增其他資訊」

**Expected behavior**
1. 顯示已新增的「工廠名字」、「工廠類型」、「工廠圖片」、「其他資訊」
2. 「其他資訊」的部分，如果不想讓第二個使用者編輯，可以顯示之前該欄位的 log。

**Screenshots**
點擊工廠補充資料
![圖片](https://user-images.githubusercontent.com/9480974/70862730-f8de2280-1f7a-11ea-8bdb-8d81e8dca185.png)

新增其他資訊
![圖片](https://user-images.githubusercontent.com/9480974/70862734-fd0a4000-1f7a-11ea-8473-4530e7d67ac3.png)

從地圖上點回該工廠資料，未有之前新增的其他資訊
![圖片](https://user-images.githubusercontent.com/9480974/70862740-04c9e480-1f7b-11ea-894a-779ca2b07541.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 6s
 - OS: iOS 13.2.2
 - Browser Chrome
 - Version 78.0.3904.84

**Additional context**

**Comment by yoyo930021** [comment]
現在的 Feature 不會更新    
會再改一下

**Comment by Yukaii** [comment]
還差 popup 顯示資訊更新

**Comment by yoyo930021** [comment]
現在已經會更新了

**Comment by yoyo930021** [comment]
更正一下 現在 popup 要先關掉再打開才會更新

**Comment by aelcenganda** [comment]
verified
