### ISSUE TITLE
Android 上傳照片時會卡住 

### ISSUE THREAD

**Issue by aaronverywin** [Disfactory/Disfactory#151]
**Describe the bug**
安卓系統照片無法上傳,會一直停留在這個畫面
![80337414_449710119048549_2790013663174459392_n](https://user-images.githubusercontent.com/51040317/71084101-82862e00-21cf-11ea-8263-e4bff06aa177.jpg)
![80090864_832642667195635_6163961630985027584_n](https://user-images.githubusercontent.com/51040317/71084116-87e37880-21cf-11ea-9ad1-53200a334850.jpg)

**Comment by aelcenganda** [comment]
related to #113 #123 #132

**Comment by yoyo930021** [comment]
413 Request Entity Too Large

Add `client_max_body_size 15m` in nginx.conf
