### ISSUE TITLE
補充工廠資訊：上傳照片沒有更新鈕可以按

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#152]
**Describe the bug**
在補充工廠資訊頁面，「新增」照片後，沒有按鈕讓上傳的照片可以成功送出，除了地理資訊欄位其他欄位都有「更新」按鈕。

所以目前無法在補充資訊頁面中新增照片

**To Reproduce**
1. 點選違章工廠圖標
2. 點選「補充資訊」
3. 「新增」照片
4.  「上傳照片」
5. 回到補充資訊頁面，無按鈕可按更新
6. 回到地圖，發現照片無更新

**Expected behavior**
在補充資訊頁面「上傳照片」後可以成功更新。

可能解法：
1. 照片除了「新增」按鈕外，另有「更新鈕」
2. 補充頁面新增「送出」按鈕
3. 照片「新增」後，若是「返回」會自動上傳

**Screenshots**
![圖片](https://user-images.githubusercontent.com/9480974/71083405-e9a2e300-21cd-11ea-9a3a-a145da2ab85d.png)

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - Safari
 - iOS 13.1.2

**Additional context**

**Comment by Yukaii** [comment]
@aelcenganda 再測試看看，應該修復了

**Comment by aelcenganda** [comment]
@Yukaii 還是沒有喔

iPhone 6 iOS 12.4.3
![圖片](https://user-images.githubusercontent.com/9480974/71322573-ed06d900-2503-11ea-8c50-cc065d6ed285.png)

**Comment by aelcenganda** [comment]
@Yukaii 抱歉我沒有測確實，目前在補充資訊頁面照片上傳的確是成功上傳了，但是因為上傳完成後沒有確認上傳成功的 success message，因此使用者不確定是否成功上傳。

related to #140

**Comment by aelcenganda** [comment]
這個解法應該要是補上上傳照片成功的 success message
`上傳照片成功`
btn: `確認`

related to #185 

![螢幕快照 2019-12-26 下午10 52 27](https://user-images.githubusercontent.com/9480974/71480244-1345b500-2833-11ea-9a5b-253ac2b0b678.png)

**Comment by aelcenganda** [comment]
目前上傳照片後有跳出確認上傳成功資訊
