### ISSUE TITLE
新增工廠：照片新增時沒填聯絡方式時無法完成上傳

### ISSUE THREAD

**Issue by Oriyar** [Disfactory/Disfactory#154]
**Describe the bug**
新增工廠照片新增時，沒填聯絡方式時就無法完成上傳

**To Reproduce**
1. 點擊「我要新增違章工廠」
2. 點擊選擇此地點
3. 點擊新增
4. 沒有填寫聯絡資訊
5. 無法完成上傳圖片

**Expected behavior**
沒有填寫聯絡資訊亦可上傳圖片

**Screenshots**
![IMG_9891](https://user-images.githubusercontent.com/55491856/71084186-b1040900-21cf-11ea-9984-654423033cf3.PNG)
![IMG_9890](https://user-images.githubusercontent.com/55491856/71084200-b82b1700-21cf-11ea-808f-4bd6852152eb.PNG)

**Smartphone (please complete the following information):**
Device: iPhone SE
Safari
iOS: 12.4.1

**Comment by yoyo930021** [comment]
related #151.
