### ISSUE TITLE
unique url for each factory

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#161]
**Describe the solution you'd like**
=> unique url for each factory
User story:

1. As a person not being around certain factories, I want to share the factory locations to people I think can take photos and report/

2. As a person who reported some factories, I want to find the factories I reported and know the reporting status of those factories.

**Describe alternatives you've considered**
1. 有留 email / 電話號碼的，舉報後會通知
2. 可輸入地址查詢附近違章工廠
3. 

**Additional context**
還需要更多研究看這個需求存不存在，先不要動

**Comment by aelcenganda** [comment]
可參考經緯度寫在網址
https://watermap.teia.tw

**Comment by Yukaii** [comment]
飲水地圖的做法可以純前端

**Comment by aelcenganda** [comment]
設計需要再加上分享按鈕

**Comment by yoyo930021** [comment]
我是覺得可以上 vue router 處理這個就是了

**Comment by Yukaii** [comment]
Ref 一下飲水地圖的做法

https://github.com/teia-tw/drinking_water/blob/f2fe7962bf9a48438eec5068e8bfe8b320f5b7e7/app.js#L6-L36

**Comment by aelcenganda** [comment]
分享按鈕在 Dev Ready 的 UI 上有
