### ISSUE TITLE
Multi allow_host support

### ISSUE THREAD

**Issue by yellowsoar** [Disfactory/Disfactory#163]
**Is your feature request related to a problem? Please describe.**
延伸自 #64 後開始支援的從 `.env` 取得 `allow_host` 功能

**Describe the solution you'd like**
將從 `.env` 或環境變數中取得以逗號/分號分隔的複數個 hostname 加入 allow_host

**Describe alternatives you've considered**
很抱歉，零妥協。

**Additional context**
建議同時支援逗號與分號分隔

**Comment by Loooffy** [comment]
一般來說

**Comment by yellowsoar** [comment]
allow_host 和 debug 之間的關係應該是這樣看，debug 時會用到的 host 只是 allow_host 的其中之一，其他的狀況像部署到正式環境、備援環境、測試環境、開發環境之類的可能會用到一組或多組的 host，譬如說把 a.disfactory.tw, b.disfactory.tw, c.disfactory.tw 都加上 cname record 導到 www.disfactory.tw，而目前的寫法只能允許輸入一組。

**Comment by Loooffy** [comment]
目前有成功可以讀到parse後的hosts們
 `['disfactory.org', 'Disfactory.org', 'disfact.org', '127.0.0.1', 'localhost']`

不過有幾個問題

1. 我用requests去打，在headers自訂一個不在allowed_host的host，requests這邊會卡住，然後server端那邊吐
```
web_1  | Invalid HTTP_HOST header: 'dis'. You may need to add 'dis' to ALLOWED_HOSTS.
web_1  | Bad Request: /
web_1  | [20/Dec/2019 05:04:01] "GET / HTTP/1.1" 400 61462
```
2. 在headers自訂一個有在allowed_host的，server端回傳
```
web_1  | [20/Dec/2019 05:06:26] "GET / HTTP/1.1" 302 0
```
在requests這邊print response出來卻是404
```
>>> re = requests.get('http://localhost:8000',headers=headers)
>>> print(re)
<Response [404]>
```

我是不是應該改用postman測試^^"

**Comment by Loooffy** [comment]
在stackexchange上讀到[關於Django的allowed host](https://security.stackexchange.com/questions/45687/what-does-djangos-allowed-hosts-variable-actually-do)

看起來Django似乎是用requests header裡的host去組成URI，而非直接用browser網址列的URL去
所以可能會有injection的危險(例如在header的host中植入有風險或未被允許的URI)，以致於有"allowed" host這個解決方案。

是否可以理解成，在實際應用上，我們用CNAME record使DNS遇到提供不同服務的a,b,c都轉到www的IP這台主機，然後主機再用header裡的host去組成URI，決定提供什麼服務；另外，為避免被inject，allowed host就要限定在a,b,c,www這4個host上。

這樣看，應該把從debug、測試、正式等等可能用到的host都列上去就行，不必區分開發階段或環境。

**Comment by yoyo930021** [comment]
@Loooffy `dev.disfactory.tw` 是前端的網址目前放在 gh-pages 上
所以跟後端環境無關 你只會發現地圖上沒有任何地點

**Comment by yellowsoar** [comment]
> 看起來Django似乎是用requests header裡的host去組成URI，而非直接用browser網址列的URL去
> 所以可能會有injection的危險(例如在request header的host中植入有風險或未被允許的URI)，以致於有"allowed" host這個解決方案。
> 
> 是否可以理解成，在實際應用上，我們用CNAME record使DNS遇到提供不同服務的a,b,c都轉到www的IP這台主機，然後主機再用header裡的host去組成URI，決定提供什麼服務；另外，為避免被inject，allowed host就要限定在a,b,c,www這4個host上。
> 

這有不同的解決方案，
dns => virtualhost(reverse proxy) => http server => WSGI => Django 
只要有一層不給過就會請求失敗。

> 這樣看，應該把debug、測試、正式等等各種環境可能用到的host都列進allowed_host就行，不必區分開發階段或環境。

一般來說不會這麼做，而是只設定需要的 hostname ，也就是嚴格白名單制。
