### ISSUE TITLE
已匯入工廠資料改名：使用者看到圖標名稱為英文「 full-info:row_3」很困惑

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#166]
**Is your feature request related to a problem? Please describe.**
點擊圖標後發現名稱是  "full-info:row_3" 很困惑不知道是什麼意思，不知道是既有疑似違章工廠。

**Describe the solution you'd like**
將英文改為有意義的中文

full-info:row_3
->
既有違章工廠 No. 3
**Describe alternatives you've considered**
既有違章工廠編號3
政府普查既有違章工廠第3號

**Additional context**
雖然要舉報違章工廠是會預設進來是看到違章工廠啦，但是看到「第三列」真的不知道是什麼意思。

**Comment by aelcenganda** [comment]
@Oriyar 請你來確認最後文字顯示要寫什麼啊喔！
@stegben @jenhaoyang 今天開會跟小海討論之後，這個需要列入 1/11 之前完成的項目，你們協調一下要怎麼做。

**Comment by Oriyar** [comment]
嗨，我剛剛跟小胖討論，改成「既有違章工廠 No.＿」，也就是 full-info 變成 既有違章工廠，row＿ 變成 No. 。 @aelcenganda  你覺得呢？

**Comment by aelcenganda** [comment]
@Oriyar 沒問題喔！

@stegben 可以動了
