### ISSUE TITLE
第一次匯入的工廠狀態要設成「資料不齊」

### ISSUE THREAD

**Issue by stegben** [Disfactory/Disfactory#168]
**Describe the bug**
目前[預設 `A`](https://github.com/Disfactory/Disfactory/blob/master/backend/api/migrations/0002_load_initial_data.py#L34) (待審核)，這個詳細的意義是資料已齊全，但由於這些第一次匯入的工廠不可能有照片，所以這個狀態是錯誤的

**To Reproduce**
打開 DB 看一下就知道了

**Expected behavior**
應該改成資料不齊那個值。但考慮到狀態要重新設計，可能要看一下新的狀態長什麼樣子

**Comment by stegben** [comment]
實做上，可以直接改[這個檔案](https://github.com/Disfactory/Disfactory/blob/master/backend/api/migrations/0002_load_initial_data.py)，或是再加一個 migration 去修這些資料。

**Comment by aelcenganda** [comment]
要改成「資料不齊，2016 年以前」或是「資料不齊舊工廠」

**Comment by stegben** [comment]
fixed via #178
