### ISSUE TITLE
新增一個 API 可以 query 該工廠的 report record

### ISSUE THREAD

**Issue by stegben** [Disfactory/Disfactory#173]
**Is your feature request related to a problem? Please describe.**
使用者會想看到該工廠過去的修改紀錄

**Describe the solution you'd like**
新增一個 API `GET /factories/{factory_id}/report_records`

**Describe alternatives you've considered**
也是可以在原本的工廠 query 裡直接帶進去，但這樣可能就會很大包。

**Comment by stegben** [comment]
這是下一個 milestone 的 high priority

**Comment by aelcenganda** [comment]
可能解法：
1. related #161 unique url for each factory
2. 提供新增建工廠編號

**Comment by mhshih** [comment]
1. 重啟開發環境
2. 請教stegben提示
