### ISSUE TITLE
「現在位置」地圖顯示清楚+顯示使用者面向方位

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#182]
**Is your feature request related to a problem? Please describe.**

Problem:
在現場實測時
1. 原本的藍框框圓圈，使用者看不清楚自己目前的定位 #135 
2. 在農田間使用時，不熟悉該地方位的話很難與地圖對照標記正確位置。
3. 使用者不確定「現在位置」的定位準確度

**Describe the solution you'd like**
針對上述三個問題：
1. 「現在位置」的 Icon 變大，至少要實心
2. 指示使用者手機現在的面向方位（箭頭、三角形、視角都可以）
3. 加上定位準確度的誤差半徑圓圈（nice to have）

**Describe alternatives you've considered**
1. 和 2. 一定要改
3. 是 Nice to have，因為重度使用者可能會回家仔細研究地圖再標記，是可以放到下個 milestone 討論要不要讓他們可以直接在界面上輸座標。

**Additional context**

**Comment by yoyo930021** [comment]
已完成
