### ISSUE TITLE
工廠 status 種類＋圖標更動

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#183]
## **Is your feature request related to a problem? Please describe.**
本來我們以為從政府公開資料取得的既有違章工廠清冊，只是缺乏照片來舉報，因此網站上線後新舉報的違章工廠跟有照片的既有工廠是相同的。

所以我們對於工廠狀態的資料欄位只設計了：
- 資料齊全
- 資料不齊
- 已舉報

從政府公開資料匯入的違章工廠資料為農委會清查在 2016 年 5 月 20 日之前的既有違章工廠。

**然而，工輔法子法公告後，對於 2016.5.20 前後的違章工廠會採取不同的政策：**
- 2016.5.20 前既有的違章工廠，會輔導登記納管，並針對中高污染的開罰。
- 2016.5.20 之後新增建的違章工廠，則拆除。

因此需要在地圖上和資料庫裡區分既有工廠與新增建工廠。

### User Story
[1] 地公工作人員
1. I want to know the factories I am going to report are new or existing factories before 2016.5.20,
So that I can prioritize and file the reports differently

2. 
I want 舉報人能知道他舉報的工廠是既有違章工廠還是新增建違章工廠，
So that 舉報人可以理解對於既有工廠或新工廠的舉報結果不同，不會怪罪地球公民基金會舉報不力。

[2] 舉報人
I want to 
So that 
> 對於舉報人來說好像沒有什麼差

[3] 既有違章工廠工廠主
I want 我的工廠不被標定為新增建的違章工廠
So that 我的工廠不會被惡意認定為新增件違章工廠而被拆除或名譽受損

### Solution I suggest
**不更動地圖圖標，使用文字加註**
因為怕太多種地圖圖標，使用者會混淆。
建議維持原有三種圖標設計，因為地圖上最重要的還是哪些工廠需要補資料
- 資料齊全
- 資料不齊
- 已舉報

關於既有工廠與新增建工廠的標註，是比較次一級的資訊，不需要凸顯在第一層。

我建議用文字標註：
在地圖的部分只顯示在目前「待審核」狀態的小字上。
例如：「資料齊全 | 既有違章工廠」
我覺得在這一層也可以選擇不要顯示，只顯示「資料齊全」
![螢幕快照 2019-12-26 下午10 22 22](https://user-images.githubusercontent.com/9480974/71479207-60735800-282e-11ea-9d72-811f3c94bfda.png)

在補充資訊的頁面
在「工廠類型」的下面附上一行小字：「105.5.20 前既有違章工廠」
![螢幕快照 2019-12-26 下午10 25 49](https://user-images.githubusercontent.com/9480974/71479303-bcd67780-282e-11ea-8085-23039124ae12.png)

需要再跟 @Oriyar 確認顏色的優先層級：
是資料不齊還是資料齊全優先顯示？也就是哪一個圖標應該是紅色的？

**資料庫架構我建議改成** @stegben 
- 工廠有兩種屬性
    - 既有違章工廠 | 2016.5.20 前
    - 新增建違章工廠 | 2016.5.20 後
- 工廠資料有三種狀態（status）：
    - 資料齊全（定義：有位置 and 有照片 and 半年內更新）
    - 資料不齊（定義：無照片 or 半年未更新）
    - 已舉報（定義：地球公民基金會向政府舉報）
    - 已拆除（目前還沒有，未來希望有這個 status!!!）

問題待確認： @Oriyar 
既有違章工廠有可能會變成新增件違章工廠嗎？
例如既有違章工廠擴建，希望是在原本的點上繼續舉報，還是新開一個工廠舉報？
對於資料庫的差別是，需要知道工廠的兩種屬性是不是互斥的，還是同一個工廠有可能既是「既有違章工廠」又是「新增件違章工廠」。

### Past discussion
一開始設計師 Sandra Lin 聽到這個需求後立刻畫了新的五個圖標：
https://app.zeplin.io/project/5ddd1713b91a321bf42ffde5/dashboard

資料齊全新工廠
資料齊全舊工廠
資料不齊新工廠
資料不齊舊工廠
已舉報

![螢幕快照 2019-12-26 下午10 01 46](https://user-images.githubusercontent.com/9480974/71478573-59971600-282b-11ea-8b57-5f185113a438.png)

=> Concern: 
1. 顏色和圖標種類過多，使用者很難理解記住五種的差別。目前的配色對於色弱者也不清楚。
2. 使用者真的需要第一眼知道既有工廠與新增建工廠的不同嗎？ => 可能不用

## **Additional context**
後端：
需要更改 factory status 種類
related to #4 #168 

前端：
新的顯示

**Comment by stegben** [comment]
後端的部份我可以多加一個欄位，拿來標注是否是 2016 以前的

**Comment by aelcenganda** [comment]
今天與 @Oriyar 、Sandra 、小胖的討論結果：

![圖片](https://user-images.githubusercontent.com/9480974/71681554-f592c580-2dc7-11ea-9b75-959d3c1960bd.png)

## 後端：
@stegben 

**新增欄位**
新增建工廠/既有工廠狀態標記的欄位

注意：因為不同政府清冊可能會名稱不同、經緯度差異，未來可能會有手動加入、移除、修改位置或整併的需求（如果有人抗議名單錯誤）。

**資料齊全/資料不齊定義改變**
- 既有工廠
    資料齊全 == 位置(v)＋照片(v)＋工廠類型(v) + 一年未更新
    其他為資料不齊
- 新增建工廠
    資料齊全 == 位置(v)＋照片(v) + 一年未更新
    其他為資料不齊 

既有工廠的工廠類型，在未來出報表給地球公民基金會的時候，會用特定工廠類型來拉中高污染類表，優先舉報。

## 前端
@Yukaii , Sandra 這週末會生出新的設計圖，以下是先讓你了解 spec，最後以 Sandra 設計圖與小海文字為準。

**Filter**
改為三種狀態：
- [ ] 新增建違章工廠
- [ ] 既有違章工廠
- [ ] 已舉報

**圖標**
目前初步討論是視覺階層在地圖上區分

1. 新增建違章工廠 vs. 既有違章工廠 
2. status(資料齊全、資料不齊、已舉報)

會有五種新圖標(前面 screenshot 的白板上方）

**地圖上點開的說明框**
- `工廠名稱`
- `新舊工廠狀態` => `old`:`105.5.20 以前既有違章工廠`, `new`:`新增建違章工廠`
- `資料完整程度` => `資料不齊`: `急需補充資料`, `資料齊全`:`請持續補充` （換掉`資料齊全`因為怕大家不補充已經有完整資料的工廠了，例如已經有照片但是照片拍很爛）
@yellowsoar 建議資料不齊的部分不用只顯示`急需補充資料`，可以顯示`還缺 4 項資料`，或是`還缺照片、工廠類型`，這部分就看你要不要做了。

> 未來地圖上點開的說明框會想要優先顯示照片而不是工廠名稱，因為工廠名稱可能不清楚。但這是下個 milestone 再談了。cc @stegben 

## 設計

需要 deliver 的東西：
1. 新的 pin
2. 新的地圖說明框
3. 新的補充資訊頁面 => 這部分我建議我不要大改排版，加上一行小字標明`新增建違章工廠`或是`105.5.20 以前既有違章工廠`即可。
4. 新的 filter 頁面 with new pins

要達成的效果：
1. 引導使用者優先去補齊新增建違章工廠的資料，要打政策要從這裡
2. 既有違章工廠的資料也需要人補齊，所以不能太弱化隱藏在地圖上，主要是要大家回報照片和工廠類型以鎖定中高污染。
3. 資料補齊後要跟缺資料的 pin 有些微不同，讓舉報者有滿足感。
4. 在資訊頁面註明新舊工廠，讓使用者質疑為何不舉報或舉報不同步時，地公可解釋處理新增建和既有違章工廠的策略不同。

**圖標**
目前初步討論是視覺階層在`瀏覽地圖`時區分

第一階層：新增建違章工廠 vs. 既有違章工廠 
第二階層：status(資料齊全、資料不齊、已舉報)

預計會有五種新圖標(前面 screenshot 的白板上方）

**地圖上點開的說明框**
- `工廠名稱`
- `新舊工廠狀態` => `old`:`105.5.20 以前既有違章工廠`, `new`:`新增建違章工廠`
- `資料完整程度` => `資料不齊`: `急需補充資料`, `資料齊全`:`請持續補充`

**Comment by aelcenganda** [comment]
@oriyar
我打完後才發現，按照目前的定義
`新增建違章工廠`不會有`資料不齊`的狀況，因為只要有照片+位置+一年內更新，就是資料齊全囉，這在新增點位的時候就已經全部要求了。所以使用者去補`新增建違章工廠`資料的時候（例如加上工廠類型），不會有任何介面上的變動讓他知道有差（顏色、形狀、文字都不會換）

還是你希望再拆成
`data` 有 `資料完整` 、`資料不齊`，`資料完整`指的是每一格都有填，且一年內更新
`status` 有 `待舉報`、`可舉報`、`已舉報`，只有`已舉報`會顯示給使用者看，`可舉報`是延用之前`資料齊全`的定義

@stegben 我剛剛打錯判斷式了，email 裡寄出去是錯的，上面已修改。但是這則寫給小海的回應你幫忙看一下有沒有問題 QQ

**Comment by aelcenganda** [comment]
我剛剛看其他 issue #168 才發現，`資料齊全`也許可以改成 `待送件`，這樣就不會讓人誤會不需要補資料啦？但也許反而會造成地公的壓力發現有很多資料齊全的還沒送件，而且既有工廠還要考慮中高污染才會列入送件。

**Comment by stegben** [comment]
根據上面的敘述以及和 @aelcenganda 的討論之後，會有如下更動：

- 「資料齊全與否」就不會是 DB 裡的欄位，而是直接從其他 field 來判斷 ，比如說 `images` 是否為空 array，最新的 `report_record` 是否在一年內等等。
- 新增「是否為既有工廠」 boolean field 在 DB 裡。
- 新增「舉報狀態」Char Eum field 在 DB 裡

**Comment by aelcenganda** [comment]
UI 更新，但是有一些細節我還要再修，已 comment 在 Zeplin 上
https://app.zeplin.io/project/5ddd1713b91a321bf42ffde5/dashboard

主要更新有：
1. 地圖上 Pin 樣式
2. 地圖 pop-up 訊息設計：為了可以更清楚交代新建違章工廠和既有違章工廠的差異，還有資料補齊的資訊。

但是地圖 pop-up 設計理想版改動過多，需要與工程師討論。 @Yukaii @cph

我的目標是 1/13 上線要穩，不想要做過多改動。

## 地圖上 pin 樣式

分四種：
- 新建違章工廠
- 既有違章工廠
- 既有違章工廠（資料不齊）
- 已舉報

@Oriyar ，請你確認一下 filter 要不要顯示資料不齊的圖標

Zeplin：
https://app.zeplin.io/project/5ddd1713b91a321bf42ffde5/screen/5e032f9ebbb6d9172daa4b67
https://app.zeplin.io/project/5ddd1713b91a321bf42ffde5/screen/5ddd17c5cddad2111754b224

## 地圖上 pop-up 訊息設計（待討論）

這個部分有兩個版本，一個是理想版，一個是最低限度改動的版本。理想版因為要費的工比較多，所以需要跟前後端討論。即便是理想版還有一些小細節不連貫， UI 還要再修。（我已標註在 Zeplin 上）

### 理想版
圖片：
<img src="https://user-images.githubusercontent.com/9480974/71805373-0c276e00-30a1-11ea-8460-8737887151d7.png" alt="alt text" width="160" ><img src="https://user-images.githubusercontent.com/9480974/71805374-0cc00480-30a1-11ea-93c2-209e331a452c.png" alt="alt text" width="160" ><img src="https://user-images.githubusercontent.com/9480974/71805376-0cc00480-30a1-11ea-9898-77558169777e.png" alt="alt text" width="160" ><img src="https://user-images.githubusercontent.com/9480974/71805377-0cc00480-30a1-11ea-847a-8da32352d2ad.png" alt="alt text" width="160" >

在顯示資訊上

1. 拿掉工廠名稱，換成「新建違章工廠」/「既有違章工廠」/「已舉報」與加上「編號」
> 原因：很多工廠可能會沒有名稱，不是主要區別的點，但是拿掉工廠名稱又會無法判斷兩個工廠的點的差別，於是決定保留編號。
> 於是就會出現「新建違章工廠」也需要一個編號。（既有工廠沿用既有編號）=> 後端要新增一個欄位。但是 request 還是用 hash。新增建違章工廠是從第一個新增建違章工廠舉報開始編號。

2. 加上「是否缺照片」與「工廠類型」兩個顯示資訊
- 已有照片/缺照片
- XXXXXXX/類型不明
工廠類型若是 len > 7，只留七個中文字。

3. 加上「最後更新日期」
-   <24 hr : 1 天內
- >= 24 hr and <30 d : XX 天前
- >=30 d and < 1 y: X 個月前
- >= 1 year: X 年前

> 這裡需要後端加欄位： last_updated_time, related to  #173 

4. 地圖 pop-up 資訊框的邊線和補充資料按鈕邊線，隨著圖標顏色改變。
5. 資料不齊的工廠，"補充資訊" 按鈕為該圖標顏色。（UI 圖上未做出，我不確定是不是設計師改動設計）

### 簡單版
1. 加上「新建違章工廠/既有違章工廠」、「是否缺照片」、「工廠類型」 3 個顯示資訊。（目前 UI 的圖還缺「新建違章工廠/既有違章工廠」的 tag ）
2. 不對新建工廠加入新編號
3. 不加上最後更新日期
4. "補充資料"按鈕不更動

> 其實還漏了在補充資訊整頁的 page 中加上新舊工廠的 tag。

### 個人意見

我傾向簡單版，因為最後一個禮拜越多改動會有越多 bug，要做好準備選後 1/13 突然要上線。
而且還需要工程人力去搬到 disfactory.tw。

**Comment by aelcenganda** [comment]
最後選擇簡單版。

**Comment by aelcenganda** [comment]
但紅色圖標會有 bug，所以改顏色為藍色、灰色。

![圖片](https://user-images.githubusercontent.com/9480974/72440984-d1ca7900-37e4-11ea-958d-d6a15b72ec89.png)

**Comment by aelcenganda** [comment]
新的藍灰色圖標

![圖片](https://user-images.githubusercontent.com/9480974/72441265-59b08300-37e5-11ea-8191-3b4302eebde9.png)

**Comment by aelcenganda** [comment]
目前差資料不齊的工廠補齊資料後圖標沒有變。
