### ISSUE TITLE
補充資訊頁面：「更新」success message

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#185]
**Is your feature request related to a problem? Please describe.**
1. 使用者會不知道修改文字欄位後按「更新」
2. 按下「更新」後只有按鈕短暫變成淺綠色，使用者不確定是否更新成功

**Describe the solution you'd like**
按下「更新」按鈕後，更新成功跳出成功訊息：

`感謝您新增資訊！`
btn: `確認`

可以使用跟新增工廠頁面送出後的同一個 pop up design
![螢幕快照 2019-12-26 下午10 52 27](https://user-images.githubusercontent.com/9480974/71480097-6cf9af80-2832-11ea-8673-b39ca126a31f.png)

**Describe alternatives you've considered**

補充頁面也可以多欄位更新後，如同「新增工廠資訊」按下「送出」按鈕。
=> @Yukaii 說這個比較麻煩一點

**Additional context**

**Comment by Yukaii** [comment]
resolved in #118
