### ISSUE TITLE
新增工廠頁面可直接輸入座標

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#187]
**Is your feature request related to a problem? Please describe.**
比較積極舉報的使用者怕我們系統的定位不準，會舉報錯誤，因此希望知道選擇的點的座標或是直接輸入座標。

比較專業的舉報為了確認舉報的經緯度和地號精準，會在現場拍工廠建築物以外，會拍攝附近的電線桿/路燈號碼、住家、路口、自繪小地圖、算從路口過來第幾塊田，搭配在 Google Map 上截圖看目前定位。回到家之後才用電腦，比對精確定位，用以上照片和 Google 衛星照片，然後得到經緯度後查地號舉報。因為他們不想在現場逗留過久，而且曾經有舉報錯誤，所以很謹慎。

related to #139 顯示比例尺和坐標
因為有第二位使用者因為怕定位不準，希望能夠直接輸入座標了，所以開一個新的 issue。

**Describe the solution you'd like**
有兩種方法：

1. 在選擇地點時可顯示座標數字，讓使用者精準定位
2. 在新增地點時可直接輸入座標

**Describe alternatives you've considered**
需要再研究使用者比較喜歡哪個方式，以及使用場景與需求，然後出圖。
也有可能專業的舉報者喜歡自己發文給政府，或是做好報告給地球公民基金會，不需要使用本系統。

第三種方法是顯示目前定位的誤差半徑。related to #182 現在位置 icon

**Additional context**

**Comment by yellowsoar** [comment]
如果要做這個功能，
那在台灣會用到的座標系：

* TWD67TM2
* TWD97TM2
* TWD67 https://epsg.io/3821
* TWD97
* WGS84

另外後三者除了度之外還有度分秒格式。
https://epsg.io/?q=TWD67+OR+TWD97+OR+WGS84

台電的電線桿參考這個：
http://61.216.174.87/
後台的 API
http://61.216.174.87/tpcGoogleMap/api/get_taip_loca_tab?FieldText=B3729DE2437

**Comment by aelcenganda** [comment]
使用者怕座標飄掉會舉報錯誤。

這個 Issue 是要使用者研究確定有沒有列入開發功能

**Comment by aelcenganda** [comment]
在兩週的資料搜集與和使用者確認後，發現專業 NGO 會標註座標和段名（目前四件），一般其他人回報時可能會提供段名或地址（不包含前述四件有 9 件），目前總共有效回報約 75 件。

標注座標原因：
1. 怕系統定位不準
2. 不會在當下在工廠前回報，而是之後到安全地點後才回報。

# 座標：

可能解法，兩個並行
1. 在紅點選擇地點那頁顯示座標、在編輯資訊頁面也顯示座標。就顯示國際通用的座標，Google Map 和我們系統使用的，然後標注是該系統。
2. 讓使用者回報時可以輸入座標：
    @yoyo930021 建議可以讓使用者在選擇地點時輸入座標，然後畫面正中央的紅點可以跳到該經緯度位置，仍然使用同一個按鈕進行正式選定地點回報。需要請設計師再研究。

# 顯示段名
在新增地點後在編輯頁面上顯示段名。至於段名輸入的部分，可以讓他們在補充資訊再寫就好。
這個需要跟 @stegben 確認來不來得及拿到段名顯示出來。
