### ISSUE TITLE
待討論：資料授權與使用者條款

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#188]
**Is your feature request related to a problem? Please describe.**
1. 目前我們程式碼是 MIT 授權，但是所收集的資料還沒有授權。最好一開始要講清楚，避免後面起爭端。
2. 另外，如果有空最好來弄一下使用者條款，避免法律疑慮。

**Describe the solution you'd like**
1. 資料授權：建議 CC0，所有使用者提供的資訊都是公共領域。代表所有人都可以拿 disfactory 上的資料再利用。
2. 使用者條款：隱私政策、需要使用者同意我們收集 cookie（我們有用 GA 追蹤要寫清楚）

**Describe alternatives you've considered**

**Additional context**
覺得包括地公要對系統上的舉報資訊負責到什麼程度。
如果不實舉報會不會下架之類的。

**Comment by yellowsoar** [comment]
補充一下不是用 CC0 授權的開放內容社群：
https://www.openstreetmap.org/copyright
https://zh.wikipedia.org/wiki/Wikipedia:CC_BY-SA_3.0协议文本

**Comment by aelcenganda** [comment]
噢噢，我本來以為沒有辦法每一筆資料標注貢獻者，因為很多人會是匿名。

所以看起來是可以 
`CC-BY-SA © 農地違章工廠舉報小幫手貢獻者`

**Comment by aelcenganda** [comment]
CC BY-SA © Disfactory Contributors
CC BY-SA © 農地違章工廠舉報小幫手貢獻者

**Comment by aelcenganda** [comment]
既有工廠資料來源：
https://maps.nlsc.gov.tw/
https://gist.github.com/ronnywang/f8bbf008e641b296c755f0167b51a550

July 30, 2019

**Comment by aelcenganda** [comment]
不對，比較好的寫法是 ODbL
https://opendatacommons.org/licenses/odbl/

```
OpenStreetMap 為開放資料，以 OpenStreetMap 基金會（OSMF）採用的 Open Data Commons 開放資料庫授權條款（ODbL）授權。

您可以自由地複製、散布、傳輸及修改我們的資料，前提是您須標明作者為 OpenStreetMap 及其貢獻者。若您在我們的資料上作修改或據之衍生其他資料 ，則只可依相同授權條款散佈有關成果。授權的法律原文詳述您的權責。

我們地圖影像塊的製圖法以及我們的文件，以創用CC 姓名標示-相同方式分享 (CC BY-SA) 2.0版條款授權。
如何標明作者是 OpenStreetMap

我們要求您以“© OpenStreetMap 貢獻者”標明作者。

您亦須清晰註明，有關資料可透過開放資料庫授權條款取得。若使用我們的影像塊，則須註明其製圖法是按 CC-BY-SA 授權。您可以透過連結至此版權頁以作註明。您亦可以指明並直接連結至授權內容 (但若您要以資料形式發布 OSM，這是必要條件) 。在無法作出連結的媒體 (如印刷品) ，我們建議你引導你的讀者至 openstreetmap.org (如註明 OpenStreetMap 的完整網址) 、opendatacommons.org，及 (如相關的話) creativecommons.org。

對於可瀏覽的電子地圖，標明出處的文字應放在地圖的一角。 例如：

如何在網頁上署名 OpenStreetMap 的例子
```

**Comment by aelcenganda** [comment]
@Oriyar 
Cofacts 真的假的 Linebot 有針對編輯所提供的資料做團隊免責和爭議處理的寫法。
https://hackmd.io/mFSlWs4IQke_9RnFAOWlfQ

**Comment by aelcenganda** [comment]
@Oriyar 

我建議改成這樣，但可能也需要你們基金會的法律專家看過。目前是把著作權歸到地球公民基金會，但關於經緯度的資訊要不要歸類成「事實性資訊不受著作權法保護」就看你們了。


# 資料貢獻協議

農地違章工廠舉報小幫手（Disfacotry）貢獻協議

感謝您有意願貢獻資料及相關內容（以下統稱「內容」）至農地違章工廠小幫手（Disfactory，以下簡稱「本網站」）。此貢獻協議（「協議」）存在於您及本網站管理機關地球公民基金會（「管理者」）間，目的在釐清雙方相關智慧財產權利狀態及其他權利義務關係。請閱讀以下條款及條件並確認，當您回報或上傳內容至本網站時，即表示您接受本協議內容。

1. 貢獻內容之合法及適當狀態

您的資料貢獻不應侵害他人之智慧財產權利。如您貢獻內容，代表就您所知您表示，您有權授權管理者及本網站的使用者，依管理者指定、揀選的授權條款，來使用並散布這些內容。

請注意管理者並不必然需要將您貢獻的內容包括於本網站上，並且得以在任何時候，將您的貢獻於本網站移除。對您貢獻的內容，管理者並無負擔保管責任。

2. 授與權利

您在此授與管理者全球性、免授權金、非專屬、永久、不可撤回之著作權及其他司法管轄區域可能定義之鄰接權及資料庫權之權利，讓其能夠不受前述權利限制使用內容之任何內含物，無論是就原始載體，或採其他型態進行利用。所授與的權利明示包括商業性使用，並且不排除任何領域內的利用。此一授權包括並不限於，將作品進行後續再授權利用，並允許多階的被授權人皆得採再授權方式再作利用。就現行法及著作權契約可容許的最大範圍內，您對管理者或經其授權利用內容之人，亦拋棄或不主張任何著作人格權。

除本處訂明之範圍，您所貢獻內容之所有權利、地位，及利益，仍保留在您。

3. 免責聲明

在現行法容許的範圍內，您是以現狀及現有之基礎提供本內容，且未聲明或提供關於該內容之任何保證。
除依法不得事先排除或限縮之責任外，您或管理者皆不應依此協議，為其他歸責理論導致任何損害賠償。

4. 其他事項
您所提送之表單及因之所需之註冊、登入程序裡，產生或由您填註的個人資訊，您在此同意管理者後續蒐集、處理及利用該個人資料。

本「協議」依據中華民國法律。當本協議任一條款被視為無效時不影響其他部份之有效性。

5. 輔助條款
除採前述貢獻提供內容外，您亦可透過表格、附錄，補充「描述」欄位說明的方式，表達您指定特一款或多款公眾授權條款，或宣告模式為輔助授權條款之意向。此時該等貢獻內容，除依本條款第2條規定之方式授權本網站外，同時亦依指定條款雙重／多重授權予本網站。

您所指定的輔助條款，並不拘束管理者，但在處理方式容許的前提下，管理者得尊重您的指定，除依管理者指定、揀選的授權條款外，同時一併採用輔助條款來散布該等貢獻內容。

倘您於輔助條款裡列入「CC0 公眾領域貢獻宣告」，該宣告模式為著作權及相關權利的拋棄聲明，解釋上本網站得不受任何著作權利與相關權利之限制，自由使用該等貢獻內容，並亦得再採 CC0 宣告模式散布該等貢獻內容。

> 最後這個輔助條款，因為我們在更新的時候是單筆更新，所以會沒辦法讓每筆都可以指定授權方式，可能需要拿掉。

**Comment by deeper747** [comment]
### **隱私權政策**
（修改TBN條款寫成）

**適用範圍**
本處所述隱私權政策，適用於您在Disfactory網站活動時，所涉及有關個人資料的蒐集、處理及利用。

使用者持續使用Disfactory網站服務，即視為當事人明示同意下述之資料蒐集、處理，及利用方式。

Disfactory得將您貢獻之內容推送至其他平台，如臉書、Instagram等社群網路平台，於推送後就該平台之個人資料使用事宜，後續悉由該平台依其隱私權政策進行處理。

**Disfactory蒐集使用者資料**
使用者自主填註的各項個人識別資料，僅作為認證、授權標示，與相關通知、聯繫用。

本網站會蒐集您使用之瀏覽器、照片等所記錄之地理位置（含經緯度），本項資訊僅用於回報紀錄之顯示、分析與彙整。

若使用者未自設資訊屏蔽機制，Disfactory部分功能會蒐集您的連線設備IP位址、登入時間，及使用瀏覽器等相關資訊。

**Disfactory對相關資料之去識別化與量化處理**
使用者同意Disfactory得以對其回報資料進行合理妥適之去識別化或相關數據量化的處理。

處理後的資料與其個人識別狀態無法產生連結者，便不再屬於個人資料，後續將得以不受回報目的之限制，被進行利用。

**隱私權保護政策修訂**
Disfactory將不定時修訂本項政策，以符合最新的個人資料與相關法定權利之保護規範。

使用者對Disfactory網站服務的繼續使用，視為明示同意更新版本的隱私權政策。

**回報機制**
Disfactory對於相關資料的收集，已踐履個人資料保護法及其相關法規的基礎要求，並在資料的處理及利用上，透過彙整或去識別化流程，以強化使用者的隱私防護。相關資料在處理之後，亦將進行公文檢舉與公益目的之分享。

若您對於您的個人資料與貢獻之資料有隱私疑慮，請聯絡管理者，使用者若對您相關資料有進行查閱、更正、停止利用，以及刪除的意見，亦可透過網站回報機制進行提報。

**Comment by aelcenganda** [comment]
我參考了開放文化基金會的隱私權條款，覺得要再加入幾項：
https://github.com/ocftw/v1.ocf.tw/blob/gh-pages/PRIVACY.md

個人資料的蒐集、處理及利用方式
    於一般瀏覽時，伺服器會自行記錄相關行徑，包括您使用連線設備的IP位址、**使用時間、使用的瀏覽器、瀏覽及點選資料記錄**等，做為我們增進網站服務的參考依據，此記錄為內部應用，決不對外公佈。
> 因為我們有接 Google Analytics，需要寫清楚點選紀錄都會收資料

資料之保護
    本網站採用 HTTPS (Hypertext Transfer Protocol Secure) 傳輸安全協定，利用SSL / TLS來加密封包，保護交換資料的隱私與完整性。

與第三人共用個人資料之政策

    本網站絕不會提供、交換、出租或出售任何您的個人資料給其他個人、團體、私人企業或公務機關，但有法律依據或合約義務者，不在此限。
    前項但書之情形包括不限於：
        經由您書面同意。
        法律明文規定。
        為免除您生命、身體、自由或財產上之危險。
        與公務機關或學術研究機構合作，基於公共利益為統計或學術研究而有必要，且資料經過提供者處理或蒐集著依其揭露方式無從識別特定之當事人。
        當您在網站的行為，違反服務條款或可能損害或妨礙網站與其他使用者權益或導致任何人遭受損害時，經網站管理單位研析揭露您的個人資料是為了辨識、聯絡或採取法律行動所必要者。
        有利於您的權益。

> 這個滿重要的，因為大家會擔心什麼狀況下我們會把他們填的個人資料交予公家單位，例如如果法院發出搜索票的時候怎麼辦呢？。所以這邊可能要再寫清楚一點。

六、Cookie 之使用
    為了提供您最佳的服務，本網站會在您的電腦中放置並取用我們的 Cookie，若您不願接受 Cookie 的寫入，您可在您使用的瀏覽器功能項中設定隱私權等級為高，即可拒絕 Cookie 的寫入，但可能會導至網站某些功能無法正常執行 。

**Comment by deeper747** [comment]
**### 農地違章工廠回報系統（Disfactory）貢獻協議**
　　感謝您有意願貢獻資料及相關內容（以下統稱「內容」）至農地違章工廠回報系統（Disfactory，以下簡稱「本網站」）。此貢獻協議（「協議」）存在於您及本網站管理機關地球公民基金會（「管理者」）間，目的在釐清雙方相關智慧財產權利狀態及其他權利義務關係。請閱讀以下條款及條件並確認，當您回報或上傳內容至本網站時，即表示您接受本協議內容。

**1. 貢獻內容之合法及適當狀態**
- 您的資料貢獻不應侵害他人之智慧財產權利。如您貢獻內容，代表就您所知您表示，您有權授權管理者及本網站的使用者，依管理者指定、揀選的授權條款，來使用並散布這些內容。
- 請注意管理者並不必然需要將您貢獻的內容包括於本網站上，並且得以在任何時候，將您的貢獻於本網站移除。對您貢獻的內容，管理者並無負擔保管責任。

 
**2. 授與權利**
- 您在此授與管理者全球性、免授權金、非專屬、永久、不可撤回之著作權及其他司法管轄區域可能定義之鄰接權及資料庫權之權利，讓其能夠不受前述權利限制使用內容之任何內含物，無論是就原始載體，或採其他型態進行利用。所授與的權利明示包括商業性使用，並且不排除任何領域內的利用。此一授權包括並不限於，將作品進行後續再授權利用，並允許多階的被授權人皆得採再授權方式再作利用。就現行法及著作權契約可容許的最大範圍內，您對管理者或經其授權利用內容之人，亦拋棄或不主張任何著作人格權。
- 除本處訂明之範圍，您所貢獻內容之所有權利、地位，及利益，仍保留在您。

 
**3. 免責聲明**
- 在現行法容許的範圍內，您是以現狀及現有之基礎提供本內容，但應保證該內容無侵權之虞。
- 除依法不得事先排除或限縮之責任外，您或管理者皆不應依此協議，為其他歸責理論導致任何損害賠償。

 
**4. 其他事項**
- 您所提送之表單及因之所需之註冊、登入程序裡，產生或由您填註的個人資訊，您在此同意管理者後續蒐集、處理及利用該個人資料。
- 本「協議」依據中華民國法律。當本協議任一條款被視為無效時不影響其他部份之有效性。

**5. 輔助條款**
- 除採前述貢獻提供內容外，您亦可透過表格、附錄，補充「描述」欄位說明的方式，表達您指定特一款或多款公眾授權條款，或宣告模式為輔助授權條款之意向。此時該等貢獻內容，除依本條款第2條規定之方式授權本網站外，同時亦依指定條款雙重／多重授權予本網站。
- 您所指定的輔助條款，並不拘束管理者，但在處理方式容許的前提下，管理者得尊重您的指定，除依管理者指定、揀選的授權條款外，同時一併採用輔助條款來散布該等貢獻內容。
- 倘您於輔助條款裡列入「CC0 公眾領域貢獻宣告」，該宣告模式為著作權及相關權利的拋棄聲明，解釋上本網站得不受任何著作權利與相關權利之限制，自由使用該等貢獻內容，並亦得再採 CC0 宣告模式散布該等貢獻內容。

### **隱私權條款**

**適用範圍**
　　本處所述隱私權政策，適用於您在 disfactory.tw 網站（以下簡稱「本網站」）活動時，所涉及有關個人資料的蒐集、處理及利用。此隱私權條款（「條款」）存在於您及本網站管理機關地球公民基金會（「管理者」）間。請閱讀以下條款及條件並確認，當您持續使用本網站服務，即視為當事人明示同意下述之資料蒐集、處理，及利用方式。

　　本網站得將您貢獻之內容推送至其他平台，如臉書、Instagram 等社群網路平台，於推送後就該平台之個人資料使用事宜，後續悉由該平台依其隱私權政策進行處理。

**本網站蒐集使用者資料**
　　使用者自主填註的各項個人識別資料，僅作為認證、授權標示，與相關通知、聯繫用。
　　本網站會蒐集您使用之瀏覽器、照片等所記錄之地理位置（含經緯度），本項資訊僅用於回報紀錄之顯示、分析與彙整。
　　若使用者未自設資訊屏蔽機制，本網站部分功能會蒐集您的連線設備 IP 位址、使用時間、使用的瀏覽器、瀏覽及點選資料記錄等相關資訊，此記錄為內部應用，絕不對外公佈。
　　為了提供您最佳的服務，本網站會在您的電腦中放置並取用我們的 Cookie，若您不願接受 Cookie 的寫入，您可在您使用的瀏覽器功能項中設定隱私權等級為高，即可拒絕 Cookie 的寫入，但可能會導至網站某些功能無法正常執行 。

**資料之保護**
　　本網站採用 HTTPS (Hypertext Transfer Protocol Secure) 傳輸安全協定，利用SSL / TLS來加密封包，保護交換資料的隱私與完整性。

**本網站對相關資料之去識別化與量化處理**
　　使用者同意本網站得以對其回報資料進行合理妥適之去識別化或相關數據量化的處理。
　　處理後的資料與其個人識別狀態無法產生連結者，便不再屬於個人資料，後續將得以不受回報目的之限制，被進行利用。

**與第三人共用個人資料之政策**
　　本網站絕不會提供、交換、出租或出售任何您的個人資料給其他個人、團體、私人企業或公務機關，但有法律依據或合約義務者，不在此限。
　　前項但書之情形包括不限於：
- 經由您書面同意。
- 法律明文規定。
- 為免除您生命、身體、自由或財產上之危險。
- 與公務機關或學術研究機構合作，基於公共利益為統計或學術研究而有必要，且資料經過提供者處理或蒐集著依其揭露方式無從識別特定之當事人。
- 當您在網站的行為，違反服務條款或可能損害或妨礙網站與其他使用者權益或導致任何人遭受損害時，經網站管理單位研析揭露您的個人資料是為了辨識、聯絡或採取法律行動所必要者。
- 有利於您的權益。

**隱私權保護政策修訂**
　　本網站將不定時修訂本項政策，以符合最新的個人資料與相關法定權利之保護規範。
　　使用者對本網站服務的繼續使用，視為明示同意更新版本的隱私權政策。

**回報機制**
　　本網站對於相關資料的收集，已踐履個人資料保護法及其相關法規的基礎要求，並在資料的處理及利用上，透過彙整或去識別化流程，以強化使用者的隱私防護。相關資料在處理之後，亦將進行公文檢舉與公益目的之分享。
　　若您對於您的個人資料與貢獻之資料有隱私疑慮，請聯絡管理者，使用者若對您相關資料有進行查閱、更正、停止利用，以及刪除的意見，亦可透過網站回報機制進行提報。

**Comment by aelcenganda** [comment]
![螢幕快照 2020-03-18 下午9 15 25](https://user-images.githubusercontent.com/9480974/76964385-9c194c00-695d-11ea-973d-f4a6bdecd6cd.png)

目前還沒有將可疑氣味的 section deploy 上去。
前端已修改，先關掉。

**Comment by Yukaii** [comment]
> ### ** 農地違章工廠回報系統（Disfactory）貢獻協議**
> 　　感謝您有意願貢獻資料及相關內容（以下統稱「內容」）至農地違章工廠回報系統（Disfactory，以下簡稱「本網站」）。此貢獻協議（「協議」）存在於您及本網站管理機關地球公民基金會（「管理者」）間，目的在釐清雙方相關智慧財產權利狀態及其他權利義務關係。請閱讀以下條款及條件並確認，當您回報或上傳內容至本網站時，即表示您接受本協議內容。
> 
> **1. 貢獻內容之合法及適當狀態**
> 
> * 您的資料貢獻不應侵害他人之智慧財產權利。如您貢獻內容，代表就您所知您表示，您有權授權管理者及本網站的使用者，依管理者指定、揀選的授權條款，來使用並散布這些內容。
> * 請注意管理者並不必然需要將您貢獻的內容包括於本網站上，並且得以在任何時候，將您的貢獻於本網站移除。對您貢獻的內容，管理者並無負擔保管責任。
> 
>  
> **2. 授與權利**
> 
> * 您在此授與管理者全球性、免授權金、非專屬、永久、不可撤回之著作權及其他司法管轄區域可能定義之鄰接權及資料庫權之權利，讓其能夠不受前述權利限制使用內容之任何內含物，無論是就原始載體，或採其他型態進行利用。所授與的權利明示包括商業性使用，並且不排除任何領域內的利用。此一授權包括並不限於，將作品進行後續再授權利用，並允許多階的被授權人皆得採再授權方式再作利用。就現行法及著作權契約可容許的最大範圍內，您對管理者或經其授權利用內容之人，亦拋棄或不主張任何著作人格權。
> * 除本處訂明之範圍，您所貢獻內容之所有權利、地位，及利益，仍保留在您。
> 
>  
> **3. 免責聲明**
> 
> * 在現行法容許的範圍內，您是以現狀及現有之基礎提供本內容，但應擔保所上傳的任何文件、相片及內容等資料及指述，並未有虛偽、捏造、侵害著作權或任何違反國家法令之情事，如有相關情事，上傳者明瞭自身將負擔相關法律責任，且與管理者無涉。
> * 除依法不得事先排除或限縮之責任外，您或管理者皆不應依此協議，為其他歸責理論導致任何損害賠償。
> 
>  
> **4. 其他事項**
> 
> * 您所提送之表單及因之所需之註冊、登入程序裡，產生或由您填註的個人資訊，您在此同意管理者後續蒐集、處理及利用該個人資料。
> * 本「協議」依據中華民國法律。當本協議任一條款被視為無效時不影響其他部份之有效性。
> 
> **5. 輔助條款**
> 
> * 除採前述貢獻提供內容外，您亦可透過表格、附錄，補充「描述」欄位說明的方式，表達您指定特一款或多款公眾授權條款，或宣告模式為輔助授權條款之意向。此時該等貢獻內容，除依本條款第2條規定之方式授權本網站外，同時亦依指定條款雙重／多重授權予本網站。
> * 您所指定的輔助條款，並不拘束管理者，但在處理方式容許的前提下，管理者得尊重您的指定，除依管理者指定、揀選的授權條款外，同時一併採用輔助條款來散布該等貢獻內容。
> * 倘您於輔助條款裡列入「CC0 公眾領域貢獻宣告」，該宣告模式為著作權及相關權利的拋棄聲明，解釋上本網站得不受任何著作權利與相關權利之限制，自由使用該等貢獻內容，並亦得再採 CC0 宣告模式散布該等貢獻內容。
> 
> ### **隱私權條款**
> **適用範圍**
> 　　本處所述隱私權政策，適用於您在 disfactory.tw 網站（以下簡稱「本網站」）活動時，所涉及有關個人資料的蒐集、處理及利用。此隱私權條款（「條款」）存在於您及本網站管理機關地球公民基金會（「管理者」）間。請閱讀以下條款及條件並確認，當您持續使用本網站服務，即視為當事人明示同意下述之資料蒐集、處理，及利用方式。
> 
> 　　本網站得將您貢獻之內容推送至其他平台，如臉書、Instagram 等社群網路平台，於推送後就該平台之個人資料使用事宜，後續悉由該平台依其隱私權政策進行處理。
> 
> **本網站蒐集使用者資料**
> 　　使用者自主填註的各項個人識別資料，僅作為認證、授權標示，與相關通知、聯繫用。
> 　　本網站會蒐集您使用之瀏覽器、照片等所記錄之地理位置（含經緯度），本項資訊僅用於回報紀錄之顯示、分析與彙整。
> 　　若使用者未自設資訊屏蔽機制，本網站部分功能會蒐集您的連線設備 IP 位址、使用時間、使用的瀏覽器、瀏覽及點選資料記錄等相關資訊，此記錄為內部應用，絕不對外公佈。
> 　　為了提供您最佳的服務，本網站會在您的電腦中放置並取用我們的 Cookie，若您不願接受 Cookie 的寫入，您可在您使用的瀏覽器功能項中設定隱私權等級為高，即可拒絕 Cookie 的寫入，但可能會導至網站某些功能無法正常執行 。
> 
> **資料之保護**
> 　　本網站採用 HTTPS (Hypertext Transfer Protocol Secure) 傳輸安全協定，利用SSL / TLS來加密封包，保護交換資料的隱私與完整性。
> 
> **本網站對相關資料之去識別化與量化處理**
> 　　使用者同意本網站得以對其回報資料進行合理妥適之去識別化或相關數據量化的處理。
> 　　處理後的資料與其個人識別狀態無法產生連結者，便不再屬於個人資料，後續將得以不受回報目的之限制，被進行利用。
> 
> **與第三人共用個人資料之政策**
> 　　本網站絕不會提供、交換、出租或出售任何您的個人資料給其他個人、團體、私人企業或公務機關，但有法律依據或合約義務者，不在此限。
> 　　前項但書之情形包括不限於：
> 
> * 經由您書面同意。
> * 法律明文規定。
> * 為免除您生命、身體、自由或財產上之危險。
> * 與公務機關或學術研究機構合作，基於公共利益為統計或學術研究而有必要，且資料經過提供者處理或蒐集著依其揭露方式無從識別特定之當事人。
> * 當您在網站的行為，違反服務條款或可能損害或妨礙網站與其他使用者權益或導致任何人遭受損害時，經網站管理單位研析揭露您的個人資料是為了辨識、聯絡或採取法律行動所必要者。
> * 有利於您的權益。
> 
> **隱私權保護政策修訂**
> 　　本網站將不定時修訂本項政策，以符合最新的個人資料與相關法定權利之保護規範。
> 　　使用者對本網站服務的繼續使用，視為明示同意更新版本的隱私權政策。
> 
> **回報機制**
> 　　本網站對於相關資料的收集，已踐履個人資料保護法及其相關法規的基礎要求，並在資料的處理及利用上，透過彙整或去識別化流程，以強化使用者的隱私防護。相關資料在處理之後，亦將進行公文檢舉與公益目的之分享。
> 　　若您對於您的個人資料與貢獻之資料有隱私疑慮，請聯絡管理者，使用者若對您相關資料有進行查閱、更正、停止利用，以及刪除的意見，亦可透過網站回報機制進行提報。

有更新過

**Comment by aelcenganda** [comment]
@deeper747 請你確認已放上網站後關掉這個 issue

**Comment by aelcenganda** [comment]
https://license.disfactory.tw/

我更新上去了
