### ISSUE TITLE
UI: 使用者不知道要在白色區域（農地）才能新增工廠

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#195]
**Is your feature request related to a problem? Please describe.**
如果不是身在農地區域的使用者，很容易在試用要新增違章工廠選擇地點時，發現無法「選擇此地點」，因為那個點不是農地，但是使用者舉目所見都不是農地，在台北市這樣的區域也要縮到很小才會看到農地區域，因此使用者會覺得此功能壞掉了。

**Describe the solution you'd like**
1. 加註一行字：在白色區域內選擇地點

我只是趕上線想要簡單一點的方法。

**Describe alternatives you've considered**
1. 在灰色區域不 disable 「選擇此地點」 按鈕，而是會跳出 error message 要求在白色區域（農地）內新增

或其他方式

**Additional context**
真的要舉報的環團在當地定位的話，會看到農地的。主要的麻煩是記者會時在台北的記者打開會一時間不知道如何新增。

**Comment by aelcenganda** [comment]
跟 Sandra 初步討論後，覺得可以在「選擇此地點」 button 下面，加一行白色小字：「白色區域為可舉報範圍」

**Comment by aelcenganda** [comment]
目前已加註白色小字，尚未使用者測試

**Comment by chunyenHuang** [comment]
<img width="404" alt="Screen Shot 2020-02-11 at 12 33 16 PM" src="https://user-images.githubusercontent.com/12788155/74276517-b6ab3600-4cca-11ea-9f2a-4b6badb6ce16.png">

白色小字在白色區域上看不清楚，建議可以用底色 黑底白字等

另外似乎有白色與淡黃色兩種區域？ (是否是地圖色塊疊加)

至於選擇地點部分 是否可以用坐標運算 如果落在白色區域外則disable 按鍵"選擇此地點“？

**Comment by aelcenganda** [comment]
白字應該要改成：

白色區域為農地（可回報範圍）

**Comment by aelcenganda** [comment]
更改設計在 zeplin 上了：
![螢幕快照 2020-03-18 下午9 28 09](https://user-images.githubusercontent.com/9480974/76965519-69705300-695f-11ea-8035-67414e70d1d7.png)

**Comment by aelcenganda** [comment]
已更改上線
