### ISSUE TITLE
Add compass on map

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#199]
**Is your feature request related to a problem? Please describe.**

Users have difficulties to know where they are and where to mark the factory on the map in fields.
related to #138 

**Describe the solution you'd like**
Show North direction on map, so that users can better mark the location.

**Describe alternatives you've considered**
Adding facing direction on "current location" icon (in #182)
However, the facing direction is not stably precise, it is better to add the North/compass on the map.

**Additional context**

**Comment by yoyo930021** [comment]
所以這個不需要了？

**Comment by aelcenganda** [comment]
已經做了
