### ISSUE TITLE
新增關於計劃的介紹

### ISSUE THREAD

**Issue by yuenyee919** [Disfactory/Disfactory#200]
***假設期望只是讓已經了解背景的人（例如：友好環團）參與，就可以略過這個request

***假設期望讓普通的群眾參與，那就要多加一點資料，讓大家了解這個計劃的意義。（例如：我要把網站發給住在農地附近的朋友，想他協助輸入舉報 - 他收到之後可能會感到很困惑，不知道這個計劃是甚麼，以及為甚麼要舉報）所以，希望有一個頁面可以介紹一下這個項目，例如：

1）背景 
- 甚麼是違章工廠？
- 違章工廠會對社會有甚麼影響？
- 為甚麼只集中找出在農地上違章的工廠？（這個會有助理解為甚麼只能在白色的地方新增舉報）
- 找出農地上違章工廠的意義是甚麼？
- 到最後我們希望透過這個計劃作出甚麼改變/達到甚麼結果？

2）現況
- 目前有幾多違章工廠已被記錄？
- 估計還有多少未有記錄的違章工廠？

3）舉報流程
- 當使用者舉報以後，你們收到舉報之後會怎樣處理？大概要多久時間？

這樣可以讓沒有背景的人了解這個項目，從而可能產生興趣然後參與。謝謝。

**Comment by yellowsoar** [comment]
這個 issue 有點大...看起來比較適合轉成一個 [project](https://github.com/Disfactory/Disfactory/projects)，然後拆成多個可以實際執行的項目?

**Comment by aelcenganda** [comment]
我會拆成

[ ] 地公網站一頁式網頁介紹 @Oriyar 
    - 緣起和議題背景、為何重要
    - 相關法規
    - 地公舉報流程
    - 開發文件
[ ] disfactory.tw 放 link, open new tab

**Comment by aelcenganda** [comment]
放了 landing page 了 #227
