### ISSUE TITLE
工廠圖標無法點選

### ISSUE THREAD

**Issue by yellowsoar** [Disfactory/Disfactory#204]
**Describe the bug**
使用用電信訊號時，定位點的範圍圈會蓋住工廠，使其無法被點選。

**To Reproduce**
1. 打開網站
2. 點擊定位按鈕
3. 等待定位成功
4. 點擊在定位範圍圈底下的工廠圖標

**Expected behavior**
出現工廠相關資料泡泡

**Screenshots**
![](https://user-images.githubusercontent.com/4775704/72435345-d5580300-37d8-11ea-891f-9073a8abbfda.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS 13.3
 - Browser: Safari

**Comment by aelcenganda** [comment]
測試過沒問題
