### ISSUE TITLE
middle2 維運流程

### ISSUE THREAD

**Issue by yellowsoar** [Disfactory/Disfactory#213]
# 預計有下列項目要執行：
- [x] 新增對應到 middle2 正式環境的永久性 branch
https://github.com/Disfactory/Disfactory/tree/middle2_prod
- [x] 新增對應到 middle2 開發環境的永久性 branch
https://github.com/Disfactory/Disfactory/tree/middle2_dev
- [ ] middle2 維運工徵招

# 待討論議題
- [ ] 考慮到會有已開 issue 但尚未有 PR 而需要 git force push 到 middle2 的狀況，所以前述兩個 branch 需要允許小幫手可以 force push ?!

# middle2 維運工技能
- 理解 middle2 的架構概念
  https://github.com/middle2tw/middle2
- 擁有 middle2 權限
- 會用 git 指令
- 瞭解 disfactory 所使用的後端技術
(連結待補)

**Comment by stegben** [comment]
我會建議 dev 就用 master 就好，維護三個 branch 太過複雜了

**Comment by stegben** [comment]
目前已改成 DigitalOcean 佈署
