### ISSUE TITLE
圖片更新 API 因為改成 async，回傳沒有 image_path 和 url，造成補充資料時上傳圖片時的預覽錯誤

### ISSUE THREAD

**Issue by Yukaii** [Disfactory/Disfactory#216]

**Comment by aelcenganda** [comment]
related to #189 ?

**Comment by Yukaii** [comment]
改成統一先顯示本機圖片就可以

**Comment by aelcenganda** [comment]
這個問題是對應到這個 issue 嗎？

![圖片](https://user-images.githubusercontent.com/9480974/75229988-f7886c00-57ed-11ea-8d19-5804f41a3ff2.png)

**Comment by Yukaii** [comment]
Yes

**Comment by aelcenganda** [comment]
![2020-03-18-222915](https://user-images.githubusercontent.com/9480974/76971522-4302e580-6968-11ea-8ca7-f465d1c8f68d.png)

今天看還是會有預覽問題

**Comment by aelcenganda** [comment]
可能要先用本機端的檔案預覽？
