### ISSUE TITLE
Disfactory branding

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#223]
統一中文名稱、英文名稱、 icon
SEO

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Oriyar** [comment]
正式名稱：農地違章工廠舉報系統
og title：舉報農地違章
英文名稱：Disfactory
icon：拆（可飛設計ing）
og image：忍者拿著放大鏡看工廠（可飛設計ing）

**Comment by aelcenganda** [comment]
ogtitle 和 ogimage 的技術實作 issue 開在 #159

**Comment by aelcenganda** [comment]
@Oriyar 

`ogtitle` 我建議還是要寫清楚是地球公民基金會
我建議 ogtitle 長這樣：

`舉報農地違章工廠系統` | 地球公民基金會

例如地公其他的網站。
![螢幕快照 2020-02-25 下午5 37 13](https://user-images.githubusercontent.com/9480974/75234420-8fd61f00-57f5-11ea-8c4a-72dcfd0562fc.png)

我還需要網頁的 description，50字以內，就是標題下面那排灰字

**Comment by aelcenganda** [comment]
今天討論後將「舉報」改成「回報」。

ogtitle 改成：
`農地違章工廠回報行動 | 地球公民基金會`

**Comment by aelcenganda** [comment]
跟 #159 一起關
