### ISSUE TITLE
幫新舉報違章工廠新增編號

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#224]
**Is your feature request related to a problem? Please describe.**
為了有讓人工可以判斷的工廠編號，因為目前的 factory_id 不容易讓人辨識與記憶。

**Describe the solution you'd like**
在 `factory_id` 外新增 field `factory_no`
將民眾回報與政府盤查分開編號，將會顯示在前端地圖頁面。

- 民眾回報編號：`U1`
- 政府盤查編號：`G387`

**Comment by stegben** [comment]
這個功能的目的是為了讓使用者可以回來 access 到自己舉報過的工廠，但就算變成編號，對使用者來說應該還是不容易記住。

對於這個需求，我會建議以『網址』來解。比如說使用者輸入 disfactory.tw/factory/{factory_id} 就可以直接打開那個工廠的資訊頁面

**Comment by aelcenganda** [comment]
上次跟 @deeper747 確認過，民眾回報的工廠可以跟著我們之前已經爬過的政府盤查編號繼續編下去。

但是編號的目的是為了任何人在打電話跟地公確認的時候可以方便溝通在講哪個工廠。
網址的部分，一般使用者是不會在手機上直接輸入工廠編號網址來做查詢。目前有請設計在把工廠網址分享這個 btn 做上去了。 #331 

每個工廠的 unique url 則是採用經緯度去標誌。 #161

**Comment by aelcenganda** [comment]
@LittleWhiteYA 這個是不是已經做好了？採取不分開政府和民眾回報的編號

**Comment by aelcenganda** [comment]
related to https://github.com/Disfactory/Disfactory/pull/368

**Comment by aelcenganda** [comment]
小白的部分應該做完了，差 @stegben deploy? 希望這個能在九月開給前端拿這筆資料喔，希望九月底前端可以顯示工廠編號 `display_number`
