### ISSUE TITLE
Landing page（about.disfactory.tw）(舊稱為 QA 頁）

### ISSUE THREAD

**Issue by Oriyar** [Disfactory/Disfactory#227]
讓不熟悉農地違章工廠及舉報系統的使用者可以了解更多
** 需要前端架一個one page
預計內容如下

這個網站要做什麼？
我該如何使用（影片）
有問題要怎麼聯絡（e.g. 網站壞掉、住家被誤報為工廠）
我要怎麼追蹤舉報的成效？
為何需要大家舉報（法規及CET倡議方式）
如何參與更多？
個人資料會如何被使用？

+大家可以幫忙補充

**Comment by Oriyar** [comment]
目前文字內容在這裡
https://hackmd.io/zGY7qd6qTP6WuOlaZ9AELw

**Comment by aelcenganda** [comment]
目前先放在 https://about.disfactory.tw/
但是， @Yukaii 沒有開 https 會被一些瀏覽器擋

**Comment by aelcenganda** [comment]
related to #200 新增關於計劃的介紹

**Comment by aelcenganda** [comment]
其他公民科技專案 landing page 參考：

生物多樣性網絡的回報網頁：
https://reptile.tbn.org.tw/

飲水地圖
https://watermap.teia.tw/

BikeSpace
https://torontobikeparking-staging.herokuapp.com/

FixMyStreet
https://www.fixmystreet.com/

**Comment by aelcenganda** [comment]
建議用 Strikingly 做 Landing page，使用付費方案 $8/月，可自訂網域。

@Oriyar  CET 創建新帳號

**Comment by aelcenganda** [comment]
@deeper747 已經將 strikingly landing page 建置完成，並升級成付費版使用客製化 domain。

目前已經將 strikingly 的 landing page 放到 about.disfactory.tw，在等 SSL 生效
