### ISSUE TITLE
「我要新增違建工廠」按鈕應為我要新增違「章」工廠

### ISSUE THREAD

**Issue by Oriyar** [Disfactory/Disfactory#232]
之前好像回報過一次（我可能是私訊告知山爪），總之開成一個issue囉。
請 @Yukaii 跟山爪確認如何修改～

**Comment by Yukaii** [comment]
這應該在 https://github.com/Disfactory/Disfactory/pull/214 修正了，但是還沒上到 production

**Comment by Oriyar** [comment]
噢噢原來如此。
