### ISSUE TITLE
無法上傳照片與更新資料

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#237]
**Describe the bug**
在 2/23 使用者測試時，在十一點到下午兩點多，無法上傳照片或是更新工廠類型/工廠名稱。按鈕會顯現「上傳中」、「更新中」，但超過一分鐘都無法成功更新。只有一兩次會成功。

![圖片](https://user-images.githubusercontent.com/9480974/75230645-01f73580-57ef-11ea-9ab0-2975fddc56db.png)

![圖片](https://user-images.githubusercontent.com/9480974/75230816-526e9300-57ef-11ea-8e87-17c0da815af4.png)

#middle2 的討論串：
https://g0v-tw.slack.com/archives/C59M1NZV2/p1582440107004300
#disfactory
https://g0v-tw.slack.com/archives/CNA60GZJM/p1582429844001900

後來解法是 ronnywang
「我把 taoyuan-lei-100033 的 process 重開了，現在記憶體問題好像解決了，所以是 taoyuan-lei-100033 吃掉太多記憶體的問題，看起來是早上十點半開始的，所以是不是今天大家早上在試用時有造成什麼 memory leak 問題？」

**Comment by aelcenganda** [comment]
當天 9:00 到 10:20-40 左右是第一批測試

11:20-12:10 是第二批測試

使用者回報無法資料庫無法更新上傳的時間是：11:50 am

ronnywang 發現 CPU >45% 是十二點半左右
CPU > 90% 是 2:33 pm
應該是因為記憶體吃完吃到 swap 了

ronny 表示：「我剛重開後記憶體問題就解決了，所以問題就是 qcluster 吃太多記憶體了，看起來是今天早上十點半開始的」

**Comment by stegben** [comment]
昨天測試的結果，是因為 django-q 把 task function 和 args 寫進 DB 且沒清掉，造成資料庫裡面很多大圖，嚴重影響效能。

目前在 #246 已修改成先把圖存到 file，並且在上傳之後刪掉

**Comment by aelcenganda** [comment]
@stegben 這個可以 close 了嗎？

**Comment by stegben** [comment]
可以 close 這個，改成 #261
