### ISSUE TITLE
後端 API 會回傳 503

### ISSUE THREAD

**Issue by yoyo930021** [Disfactory/Disfactory#244]
**Describe the bug**
後端 API 會回傳 503

**To Reproduce**
隨便開網頁

**Comment by stegben** [comment]
看起來是 cloudflare 把 `disfactory.tw` 的 Under Attack Mode 啟動了（不知道這怎麼 trigger 的）。目前設成 low 之後就可以正常 query 了

ref. https://stackoverflow.com/a/55748982
