### ISSUE TITLE
Imgur API 限制一個 IP 每小時只能上傳 50 張照片

### ISSUE THREAD

**Issue by stegben** [Disfactory/Disfactory#261]
https://stackoverflow.com/a/51195493

https://help.imgur.com/hc/en-us/articles/115000083326-What-files-can-I-upload-What-is-the-size-limit-

**Comment by stegben** [comment]
目前想到兩種解法：

- 由前端上傳至 imgur，再把 imgur 網址傳回後端存
- 仍由後端傳，假如已經超過這個小時的 quota ，就先存 local ，設定一小時之後再傳去 imgur

**Comment by aelcenganda** [comment]
cph:
噢對今天還想請你跟 Yukai 討論一下由前端上傳照片的事情
主要是為了解決後端一小時只能上傳 50 張的 issue (edited) 
現在後端都有把影像存下來，但不一定能上傳道 imgur，且成功上傳至 imgur 的照片，DB 裡面就失去他在本機的路徑
啊不過前端上傳的話就比較難拿到 exif
啊啊啊好多 tradeoff
ael  
失去本機的路徑會怎樣
cph  
就那張圖會存在資料夾裡面，但我們不曉得是哪張。得一張張打開來看
我會先發個 PR 把這兩種路徑都存在 DB
這樣資料比較不會丟失

**Comment by Yukaii** [comment]
https://github.com/exif-js/exif-js

也可以前端直接抽 EXIF，和圖片網址一起傳給後端

**Comment by Yukaii** [comment]
用這個來測試上傳照片的 exif 資訊

https://yukaii.tw/exif-js-demo/

**Comment by stegben** [comment]
將會透過前端上傳 imgur 來解決
