### ISSUE TITLE
後台 Admin Page 設計

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#268]
## **Is your feature request related to a problem? Please describe.**
要讓地公工作人員可以看資料和增加資料資訊。

## **Describe the solution you'd like**
- Admin Page by Django: For staffs to monitor, track and organize each factory report records 

（Dashboard 新開 issue #276 ）

## **Describe alternatives you've considered**
- Admin Page: using Google Spreadsheet or Airtable
    - Pros:
        - Easy to understand for CET staffs
    - Cons: 
        - Hard to show all the images in one cell for one factory
        - Hard to link data across tables
        - Need to rely on third party services to make the flow smooth

### Admin Page
As a CET staff

When I open Admin Page to view unprocessed factory report records,
I want to
1. know which factory is in high priority to report (high pollution or new factories after 2016)
2. know which data is trust worthy to be reporting materials and which data needs more evidences or be removed
3. know what is done and what to do next
4. collaborate with volunteers
So that I can efficiently organize raw data into printed official documents with all information needed for the government with less time and higher accuracy

When I am going to/after issue official documents to report illegal factories,
I want to 
1. know which government agency and person to report to 
2. write comments and update status on the data
So that I can 
1. officially report illegal factories to responsible local governments 
2. track each report status and progress with different government agencies
3. Update governments' responses to the community and general public

### Admin Page:
- CET staff can CRUD on data
    - Update `cet_report_status`、`是否新建`、`fact_check`，`priority`、`official_doc_print`、`official_doc_sent`、`official_doc_officer` 、`official_doc_agency` 、`official_doc_reply`，
    - soft-delete an image or a factory #275 
    - Filter and sort
    - search
- Password protection
- images preview
- one page view for a single factory:
    - Show all past edits records and logs
    - easy to print out (nice to have)
- A main table with factory_id as the key with columns as followings
    * 工廠 ID：`factory_id`， 32 位元 uuid（對現狀的描述）as the key
    * 工廠數字編號：`factory_no`，example: `U1`: 民眾回報第一號、`G300`：政府盤查第 300 號。這個數值會顯示在前端給使用者看，方便人工判讀是哪家工廠。 #224 
    * 初次回報時間：`created_at`，政府盤查的用爬蟲下來那天的時間
    * 最後更新時間： `updated_at`
    * 縣市：`county-city`，從 `行政區` 或是 `段名` 中切出來
    * 鄉鎮市：`town-district`，從 `行政區` 或是 `段名` 中切出來
    * 里：`village`，從 `行政區` 或是 `段名` 中切出來
    * 段號：`section_code`，會是英數字
    * 段名：`section_name`，中文字串
    * 地號：`landcode`
    * 經度：lat
    * 緯度：lng
    * 工廠類型：`factory_type`，在後台的時候要轉成中文對應
    * 補充資訊：`others`，每次更新為 append，並記錄更新時間 log
    * 工廠外觀文字：`name`，因為工廠外觀文字會更新，這裡 DB 要改成 append，不是 update
    * 工廠可疑原因： `factory_pollution`，選項尚未確定，可能有 `smell`、`sound`、`water`、`other` 之類的
    * 點位來源：`source`，`U`:`民眾回報`,`G`:`政府盤查`
    * 圖片連結：`image_path_all`：所有上傳至該工廠點位的
    * 圖片預覽：`image_preview_all`：顯示每張圖片縮圖
    * 首圖回報者：`first_image_contact_nickname`
    * 首圖聯絡方式：`first_image_contact`
    * 瀏覽次數：`factory_PV`，page view for each factory（用來判斷受關注程度）=> 不確定這是後端還是前端要做
    * 動作次數：`action_count`，reportrecord 裡對這個 factory 有幾筆 action。（用來判斷受關注程度）
    * 移除工廠資訊：`factory_soft-delete`，BOOLEAN，地公輸入
    * 地公舉報進度：`cet_report_status`，地公輸入
    * 2016 衛星圖：`2016_satellite` 
    * 新衛星圖：`new_satellite`
    * 新衛星圖日期：new_satellite_date 
    * 是否新建：BOOLEAN，地公輸入
    * 惡意警告：`fake_alert`，由系統判斷，提供 tag。 #照片時間（拍攝日期與上傳日期相差超過三個月） #不可信舉報人（根據 IP 黑名單判斷）#照片地點（EXIF 的經緯度位置與舉報地點相差 2 公里以上） #使用者檢舉
    * 事實查核：`fact_check`，由地公專員輸入。
    * 重要性：`priority`，系統和人工輸入提供 tag。#中高污染（由工廠類型判斷或手動加上）#新建工廠 #關注度高((`factory_PV`+`action_count`*2 )>50）
    * 公文產生：`official_doc_print` ，BOOLEAN，updated by staff
    * 公文寄出：`official_doc_sent`，BOOLEAN，updated by staff
    * 公文負責人：`official_doc_officer` （待確認），updated by staff
    * 公文局處：`official_doc_agency` ，updated by staff
    * 公文回函：`official_doc_reply`，pdf or jpg or link attachments, updated by staff
    * 政府回應：`gov_response`，選項尚未釐清，這邊是記錄政府的處理方式，e.g. 拆除、輔導納管、無回應等等。

> @deeper747 如果有多次公文來回怎麼紀錄？
> 若發現不同舉報點位為同一家工廠，該如何合併？
> 想要確認公文回函電子檔案的格式，是用掃描還是電子公文？
- Image table or page view
    - `image_id` as key
    - `image_preview`
    - `factory_no`: hyperlink to factory single page
    - `factory_id`
    - `lat` from image's EXIF
    - `lng` from image's EXIF
    - `orig_at` from image's EXIF
    - `created_at`: uploaded time
    - `contact_nickname`
    - `contact_email`, split from `contact_info`
    - `contact_phone` , split from `contact_info`
    - `ip`
- Contact table:
    - `ip` as key
    - `nickname`
    - `email`
    - `phone`
    - `image_id` list, hyperlink to image table
    - `image_preview`
    - `factory_no` list, hyperlink to factory single page
    _ `credit`: int, updated by staff，how much we trust this reporter

### Admin Page
- Sign up new accounts
- Complicated access management system, e.g. admin, editor and volunteer

**Comment by aelcenganda** [comment]
今天初步討論：

一開始的raw data可以先倒進google sheet或是airtable (爪認為：考慮說有照片，airtable可能比較合適)  欄位請參考https://docs.google.com/spreadsheets/d/1YYSrklnHhqqO79GFQQCjv-9_ZHRRdMVHwjZ4ORd07So/edit?usp=sharing
在下架功能被設計/code之前，先email地公就是了，Sandra接下來會來設計下架的UI
地公需要討論：有瑕疵的資料（照片是糊的、惡搞的資料etc）他們想怎麼應對，討論完後會跟我們說，提供我們設計更細緻的系統使用流程

**Comment by aelcenganda** [comment]
Admin Page sketch on Wednesday
![Image from iOS (1)](https://user-images.githubusercontent.com/9480974/77750042-10d73f00-705e-11ea-95ec-41bfafff185f.jpg)

**Comment by aelcenganda** [comment]
@stegben I am sorry that I complete the spec draft just by now. Please review it and let me know your opinions.

**Comment by stegben** [comment]
Seems like there are a lot of extra fields other than the pre-existing ones in DB. Would you please make a priority list of those fields?

**Comment by aelcenganda** [comment]
deeper 表示最有可能是我們寄一封公文，收到三份公文。所以至少要可以放六份公文回函，兩次公文去函。

**Comment by aelcenganda** [comment]
Admin Page field priority:

### First Priority

1. Get `行政區`、`段名`、`段號`
2. Split `行政區` to `縣市`、`鄉鎮市`、`里`
3. Add `工廠數字編號`
4. Add `可疑原因`（nice to have）

mentioned by @deeper747 in issue #279 
responded by @Loooffy in PR #278 

The following bold texts are new fields
    * **工廠 ID：`factory_id`， 32 位元 uuid（對現狀的描述）as the key**
    * 工廠數字編號：`factory_no`，example: `U1`: 民眾回報第一號、`G300`：政府盤查第 300 號。這個數值會顯示在前端給使用者看，方便人工判讀是哪家工廠。 #224 
    * 初次回報時間：`created_at`，政府盤查的用爬蟲下來那天的時間
    * 最後更新時間： `updated_at`
    * **縣市：`county-city`，從 `行政區` 或是 `段名` 中切出來**
    * **鄉鎮市：`town-district`，從 `行政區` 或是 `段名` 中切出來**
    * **里：`village`，從 `行政區` 或是 `段名` 中切出來**
    * **段號：`section_code`，會是英數字**
    * **段名：`section_name`，中文字串**
    * 地號：`landcode`
    * 經度：lng
    * 緯度：lat
    * 工廠類型：`factory_type`，在後台的時候要轉成中文對應
    * 補充資訊：`others`，每次更新為 append，並記錄更新時間 log
    * 工廠外觀文字：`name`，因為工廠外觀文字會更新，這裡 DB 要改成 append，不是 update
    * **工廠可疑原因： `factory_pollution`，選項尚未確定，可能有 `smell`、`sound`、`water`、`accident`、`others` 之類的**
    * 點位來源：`source`，`U`:`民眾回報`,`G`:`政府盤查`

**Comment by aelcenganda** [comment]
### Second Priority

1. Add `lng`、`lat` to Image table
  > extract EXIF from image is at #281
  > Imgur upload limit and whether to upload from frontend or backend is at #261
2. attach `contact_nickname` and `contact` to Image table
3. Add (nice to have)
  - `contact_email`, split from contact_info
  - `contact_phone` , split from contact_info

**Comment by stegben** [comment]
初步跟 @deeper747 討論， `cet_report_status` 改成六種狀態：`未舉報`, `第一次發文待回覆`, `第一次回文`, `第一次發文待回覆`, `第二次回文`, `已舉報`

**Comment by stegben** [comment]
2020/04/08 討論

- 輸出 csv（根據眼前 Filter 的狀態）
- For 每個工廠，下載一包 tar 檔包含這個工廠的所有照片

## `Factory`
需要增加的欄位
- 段號，段名，行政區

需要的 Filter 方法
- 有沒有 report record

需要的 Sort 方法
- 最近一筆 report record 時間

**Comment by aelcenganda** [comment]
現在最接近現狀的 spec 是 #389
