### ISSUE TITLE
middle2 部署測試

### ISSUE THREAD

**Issue by yellowsoar** [Disfactory/Disfactory#27]
# Todo

- [x] runserver
- [x] cname 設定
- [x] imgur setup
- [x] gunicorn

---

# 五四三

依據 middle2 官方說法，
安裝額外套件需要寫 `m2-build.sh`
https://g0v-tw.slack.com/archives/C59M1NZV2/p1571227020015600

geodjango 需要安裝一些 libraries：
`apt-get install binutils libproj-dev gdal-bin`
ref:
https://docs.djangoproject.com/en/2.2/ref/contrib/gis/install/geolibs/

PostgreSQL export ref:
https://middle2.hackpad.tw/-PostgreSQL-iHOYlCGlVFq

屬於 #26 一部分

**Comment by yellowsoar** [comment]
需要人工處理的部份：
在 middle2 設定環境變數(趨近於無解)

**Comment by jenhaoyang** [comment]
目前依然會使用middle2嗎  如果需要的話我可以幫忙這個issue

**Comment by yellowsoar** [comment]
> 目前依然會使用middle2嗎 如果需要的話我可以幫忙這個issue(人工處理的部分)

環境變數是要在 middle2 後台設定的，在不把環境變數加到版本控制的情況下，你打算要怎麼解決這個步驟？

**Comment by yellowsoar** [comment]
https://github.com/Disfactory/Disfactory/pull/196 之後應該就算打完收工了。 cc @pm5  @stegben
