### ISSUE TITLE
後台需求：行政區、段號、段名、地號

### ISSUE THREAD

**Issue by deeper747** [Disfactory/Disfactory#279]
**為了檢舉需要，我們需要更多國土測繪雲的既有欄位**
為了檢舉方便，地公這邊需要 `行政區`、`段號`、`段名`、`地號`，才能更容易生成公文
<img width="513" alt="截圖 2020-04-01 下午8 05 00" src="https://user-images.githubusercontent.com/60970217/78135295-3c8a6880-7454-11ea-898c-ecbec79adafe.png">

**Comment by Loooffy** [comment]
#278 

抱歉..我應該先開一個branch再發PR到backend-admin-page才對@@

先解決資料不全的問題：

>從easymap上抓下來的地籍資料有行政區、段號、段名、地號，但行政區是用代碼表示(e.g. 台北市松山區是A01)。目前的方法是到[內政部資料開放平台](https://data.moi.gov.tw/MoiOD/Data/DataDetail.aspx?oid=78E07539-9BE3-40CA-92AC-588B2B616B93) 抓了對應代碼和名稱的資料存成xml檔，之後從easymap抓資料下來，就用代碼查名稱塞回dict裡。

可改進的方向：
>考量到效率，是否應該從xml抽{代碼:名稱}的所有對應資料出來，存到資料庫的table裡？

**Comment by aelcenganda** [comment]
epic issue in #268

**Comment by stegben** [comment]
@Loooffy 把那些 xml 檔案讀進來大約需要多少時間？假如有點長的話可以寫進 DB，不然就 server 啟動時讀進 memory 就好

**Comment by Loooffy** [comment]
不好意思反應太慢 感謝review and merge!

**Comment by stegben** [comment]
沒問題沒問題，感謝你的 initial work
