### ISSUE TITLE
Extract EXIF from img before uploading to Imgur

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#281]
**Is your feature request related to a problem? Please describe.**
As a CET staff,
I want to know `orig_at`, `lng` and `lat` and from images uploaded to our system, 
So that I can better evaluate the credibility of photos as evidences to report illegal factories.

Now we have when the photo is taken, but we want to know the geolocation as well.

related to #261

**Comment by aelcenganda** [comment]
@yoyo930021 現在這個 issue 是差哪個部分所以不能關？

**Comment by yoyo930021** [comment]
It's finished.

**Comment by aelcenganda** [comment]
@stegben I just want to make sure EXIF is already stored in DB right now

**Comment by stegben** [comment]
Yes, but it seems 80% of the images has no exif date
