### ISSUE TITLE
全能工廠EP同步整合

### ISSUE THREAD

**Issue by yellowsoar** [Disfactory/Disfactory#283]
[EP同步](https://www.google.com/search?q=ep%E5%90%8C%E6%AD%A5%20%E5%87%BA%E7%89%88)

使用情境：
匯出工廠與照片成為公文(ODF, PDF)並賦予不重複的有序流水號存到資料庫(例：109001)

可能會用到的套件或軟體：
odf 生成
https://pypi.org/project/odfpy/
pdf 匯出
https://pandoc.org
https://pypi.org/search/?q=pandoc

其他考慮：
地段段號所在選區立委對應

**Comment by Loooffy** [comment]
- **初步測試pandoc**
pandoc支援md和html作為輸入格式
考慮django的template系統可以生成html，所以先以html作為輸入pandoc的格式來做測試

    >**html排版設定：**
以CSS設定格式
標題用h1
縮排與行距
段落間距用margin來實現
字型由外部的google開放楷體匯入

- **轉換結果：**
如下圖一、二，margin無法完全表現在輸出的文件上，推測word類文件和html的render邏輯不同
另外，轉換成pdf時需要額外安裝中文字型的支援，步驟稍微繁複，還需要研究
先以有支援python API的[weasyprint](https://weasyprint.readthedocs.io/en/latest/tutorial.html#as-a-standalone-program)來做測試，結果如圖三。

- **待研議：**
    幾個小問題：
    1. cet專員是否會有手動編輯文件的需求？
    >想像實際使用時，應該是cet專員在工廠資料庫管理頁面上篩選出還沒生成公文的資料，用瀏覽器預覽template生成的內容(如圖四，interpolation欄位以{{}}標注，實際生成的文件不會有符號)，確認無誤後點選打包下載。
    2. 目前html和pdf檔render出來的格式有落差，實際使用上是否需要完全一致？
    3. 匯出的檔案是否需要存在伺服器上？


#### 一、html > odt (using pandoc)
![Imgur](https://i.imgur.com/9XjqoL6.png) 
#### 二、html > odf (using pandoc)
![Imgur](https://i.imgur.com/GMp8Ar7.png)
#### 三、html > pdf (using weasyprint)
![Imgur](https://i.imgur.com/Sw3Beg0.png)
#### 四、html ![Imgur](https://i.imgur.com/7I5KF7N.png)

**Comment by stegben** [comment]
@Loooffy 看起來蠻厲害的，看要不要整進 admin page 裡？或者直接多一個 table ，紀錄每次輸出的公文，這樣同一個工廠就可以有多次公文發布

**Comment by deeper747** [comment]
給樓上大大們參考我用word合併列印出公文時doc編輯檔樣貌與excel檔欄位
word編輯檔：
![截圖 2020-04-20 下午5 51 31](https://user-images.githubusercontent.com/60970217/79740107-b74af300-8331-11ea-9927-55df111280ca.jpg)

圖上標上黃色的是每次需要變更的欄位，除了日期之外，都有在下面的excel檔對應才能插入
後台資料已有的：
- 行政區
- 受文者
- 照片

希望開放管理者下拉式選單選擇的
- 負責人

希望隨著一鍵下載自動生成並填入的
- 負責人email
- 日期
- 文號
- 受文者
- 副本受文者（目前看起來找到該選區的立法委員最困難）

excel檔（注意欄位即可
<img width="721" alt="截圖 2020-04-20 下午5 49 54" src="https://user-images.githubusercontent.com/60970217/79740145-c5007880-8331-11ea-9cfa-7a02a572a359.png">

希望週三小聚時（或之前）可以討論一下這個！

**Comment by Loooffy** [comment]
@stegben 依照目前 @deeper747 作法 用admin page既有的export to csv就能達成，似乎不用輸出成odf？也覺得可以開個table紀錄已輸出的公文。

@deeper747 立委的資料可用[中選會的選舉資料庫](https://db.cec.gov.tw/histQuery.jsp?voteCode=20200101T1A2&qryType=ctks)這份嗎？如果堪用，我可以寫個parser簡單清理一下，建一個立委-選區的table整到資料庫裡。

**Comment by Loooffy** [comment]
> @Loooffy 看起來蠻厲害的，看要不要整進 admin page 裡？或者直接多一個 table ，紀錄每次輸出的公文，這樣同一個工廠就可以有多次公文發布

@stegben 從 @deeper747 的回覆看起來似乎

**Comment by stegben** [comment]
@Loooffy @deeper747 Cool，那看起來我們就專注把欄位補齊就好

**Comment by aelcenganda** [comment]
> @deeper747 立委的資料可用[中選會提供的選舉資料](https://db.cec.gov.tw/histQuery.jsp?voteCode=20200101T1A2&qryType=ctks)這份嗎？如果堪用，我可以寫個parser簡單清理一下，建一個立委-選區的對應關係，然後整到資料庫的table裡。

g0v 社群應該有已經清好的，我不確定這份是不是，我再找一下
https://github.com/kiang/vote2020

**Comment by Loooffy** [comment]
@deeper747 ：
- 希望可以一鍵生成多個勾選中的案件的pdf，避免處理excel、word之間繁瑣的轉換。(屆時csv即可退役)。
- 載入圖片目前需要在imugr中翻找，希望能有更好的預覽方式。
- 希望可以預覽列印，可以接受html和pdf的格式誤差。

@Loooffy ：
- 處理圖片的預覽及插入
- 一鍵生成多個案件的公文
- 建立行政區與立委的對應

@yoyo930021 ：
- 正在爬立委的聯絡方式
