### ISSUE TITLE
把 db 裡不在 imgur 的圖片重新上傳到 imgur

### ISSUE THREAD

**Issue by stegben** [Disfactory/Disfactory#299]
**Is your feature request related to a problem? Please describe.**
由於過去曾有一段時間是由 server 來上傳照片，結果會踩到每小時 50 張照片的問題，因此有些照片是  server 自己處理。新的架構會由前端上傳，並統一用 imgur，因此要把資料庫裡有些自己 serve 的改成 imgur

**Describe the solution you'd like**
一個一次性的腳本，輪尋過 DB 裡的照片，看 path 是不是 imgur 的

**Comment by hanhantw** [comment]
我可以問一下路徑是存在 db 欄位裡嗎？
看不到正式的長怎樣
如果是，應該可以用 sql filter path 然後打過去 imgur ?
