### ISSUE TITLE
移除對 PostGIS 的依賴

### ISSUE THREAD

**Issue by stegben** [Disfactory/Disfactory#302]
**Is your feature request related to a problem? Please describe.**
PostGIS 的安裝其實不太容易，且需要有非常高的權限才能啟動，這對維運來說並不方便。另外，我們實際上用到的功能也只有 range query，這其實可以透過暴力計算或是 geo indexing 就可以解決

**Describe the solution you'd like**
有很多可能的方法：
- 由於工廠比數不多（數萬筆），可以直接算距離
- 用 geo indexing，比如說 [h3](https://observablehq.com/@nrabinowitz/h3-radius-lookup) ，可以得到 approximate neighbors，但可能要 benchmark 一下這和暴力解的準確度差多少

**Comment by yellowsoar** [comment]
實作的時候可以考慮先把經緯度座標轉換成二度分帶的座標，這樣資料庫記錄的就會是可以直接計算的公尺。
臺灣本島的二度分帶要用 3826 (TWD97 / TM2 zone 121)
https://epsg.io/3826

**Comment by Swind** [comment]
參考資料:
**MySQL Great Circle Distance (Haversine formula)**
https://stackoverflow.com/questions/574691/mysql-great-circle-distance-haversine-formula

之前有依照上面的說明做一個實驗用的 commit （主要是把 MySQL 指令轉成 PostgreSQL)
https://github.com/Swind/Disfactory/commit/fc04fbf82432f3bb5c5f7b730eaaeebef3cea1d7
不過還沒有做過結果的驗證

**Comment by aelcenganda** [comment]
還有 #18
