### ISSUE TITLE
有蠻多照片並沒有對應的工廠和 report record

### ISSUE THREAD

**Issue by stegben** [Disfactory/Disfactory#304]
**Describe the bug**
打開後台，看 Image table ，會看到有一些照片沒有 FK 到任何工廠或 ReportRecord

**To Reproduce**
還不確定是怎麼產生的

**Expected behavior**
照正常 API 使用流程，

**Comment by aelcenganda** [comment]
應該是因為在新增工廠時，只成功在 modal 上傳照片，但是未送出新增工廠。

**Comment by aelcenganda** [comment]
這個不是工程問題，是 UI 設計問題，已另開 UI issue #334
