### ISSUE TITLE
django admin page static files not serve

### ISSUE THREAD

**Issue by LittleWhiteYA** [Disfactory/Disfactory#306]
**Describe the bug**

用 docker-compose.yml 跑起來的 django server
點到 `localhost:8000/admin` 會抓不到 static files

**To Reproduce**
1. `docker-compose up -d`
2. 點到 `localhost:8000/admin` 會抓不到 static files

**Screenshots**

![image](https://user-images.githubusercontent.com/11289529/81820453-37e0c600-9563-11ea-8f77-3d6d356356bf.png)

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser: chrome

**Comment by TobyOoO** [comment]
在自己本機的 .env 裡面改成 `DISFACTORY_BACKEND_DEBUG=true`
開啟 django DEBUG mode 就可以暫時解決這個問題了，可能可以先把這個 workaround 放進 readme 裡面。

**Comment by stegben** [comment]
現在直接跑 `make run-dev` 即可，`docker-compose.dev.yml` 有把 `DEBUG` 設成 `True`
