### ISSUE TITLE
Admin Page Spec v0.2 (not completed yet)

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#312]
> Past discussion is in #268 Admin Page Design. This issue is the epic issue for the new spec.

目前是以 Google Doc 上而不是以 GitHub 這份為準：
https://docs.google.com/document/d/1uBqD_Ms1-HHAH1B1SCagsVZS_XKMxYDFuQHOHxkJ4_8/edit
＝＝＝＝＝＝＝＝＝＝＝＝
Three main views on Django Admin:
- [ ] 1. Determine which factory to officially report（審核照片）
- [ ] 2. Send official documents to government agencies（寄送公文）
- [ ] 3. Follow-up government responses（進度追蹤）

def. of Views: 
- not different tables in DB but different views to show on Django Admin
- One table view for one purpose as listed

### User story
As a CET staff,
When I retrieve factory report records
I want to 

    1. Check quality and authenticity of photos attached to factories
    2. Mark new factories built after 2016.5.20

So that I can

    1. Determine which factories to report on official documents
    2. Add qualified photos by myself or contributors/volunteers

#### Table View
- [ ] Browse all important table columns without horizontal sliding
- [ ] Filter:
  - [ ] customized time-frame to view => enter starting date and ending date to view
  - [ ] data sources from Users or Government
  - [ ] `cet_report_status`：want to filter out those factories that are not processed yet (地公尚未處理) #
  - [ ] `factory_type` ：工廠類型（nice to have）：方便未來篩選出中高污染之工廠
- [ ] 
- [ ] Fields showed on the table （待補詳細）
- [ ] Use `factory_no` as first column instead of `name` because there is no names in many factories report records (There is no such field yet, please add that field `factory_no` in #224) 

#### Factory single page view

Must have
- [ ] Select which reviewer is responsible (目前只會有兩個研究員，到時候產生公文時需要配合填入聯絡用 email)
- [ ] Mark `new_factory`: Yes/No/Unclear; `highly_polluted`: Yes/No/Unclear, `report_ready`: Yes/No/Pending. (`new_factory` field now is boolean, but we need `unclear` status. The later two fields have not been added in DB)
- [ ] Add notes and tags on factories that are No/Pending in `report_ready`. The tags and notes should be showed on frontend UI to general users. 
- [ ] Timestamp records for each edit from CET => to track reporting status and history
- [ ] Directly upload image on Django Admin (Because CET staffs sometimes need to supplement screenshots from Google Map or other sources) 
- [ ] Select which images to be used in official documents to government agencies (not all images are qualified to be attached in the official documents)

[nice to have]
- [ ] Embedded or a link to satellite/aerial images of that location on or slightly after 2016.5.20
- [ ] Photo authenticity alert. Using EXIF (done in #281 ) extracting from photos to alert which photos may be faked 

### Out of scope
1. Directly edit cells on table view

## 2. Sent out official documents to government agencies（產生公文）

(blank so far)
Past discussion on #283 

### User Story
As a CET staff or a volunteer,
When I follow-up the reporting process, including government responses and CET action,
I want to

1. See the past process and current status of each factory I am in charge
2. Update status and add notes to track government's responses
3. Update government agency contacts

 So that I can

1. Communicate with government agencies with all the evidences and information I need and push them for next actions
2. Collect materials and data for advocacy and social media marketing and when to followup  again
3. Know who to talk to (government agency contact updates)

#### Table view
- [ ] Filter

#### Factory Single Page View 
- [ ] Add new fields in DB to track government responses and CET actions @deeper747 待補
    - 農
    - 地
    - 違建
    - 工廠
    - 中央
    - `gov_response_summary`
    - `cet_report_status`: existing fields but new list of status ( 待補)
- [ ] Add new field: `followup_person` => should link to access management system
- [ ] `followup_memo` (待補)
    - 
    - 
- [ ] change status of ``(待補)
- [ ] Upload jpg or pdf of government's responding official documents, which will be showed on frontend UI as well
### Out of Scope

**Comment by deeper747** [comment]
![截圖 2020-05-22 下午3 50 13](https://user-images.githubusercontent.com/60970217/82992600-f3a8f780-a031-11ea-977b-ecb5c5df3c66.png)
這個是審核照片時需要的欄位（們），包括
- factory_id
- 行政區
- 段號
- 段名
- lng
- lat
- 工廠類型
- others
- name
- image_path
- img_preview

到時候在後台，其實我每一間都會點開來，所以審核時會希望是「單筆的pageview」（也就是現在django的模式）。主要會希望
1. 點開圖片方便
2. 可以選擇好到時候「一鍵下載公文」時會用到哪張照片
3. 可以自動生成一個google maps網址，自動填入經緯度，方便去街景對照現況查證，或截圖街景補充舉報證據

**Comment by deeper747** [comment]
我們（潦草）的user story原樣

0. 全部流程
![00全部流程](https://user-images.githubusercontent.com/60970217/82997094-8056b400-a038-11ea-8023-69944554db03.jpg)

1. 審核回報
![01 審核回報](https://user-images.githubusercontent.com/60970217/82997100-851b6800-a038-11ea-83e4-42e615c27ad0.jpg)


![01 審核回報2](https://user-images.githubusercontent.com/60970217/82997103-864c9500-a038-11ea-9c86-7b9070e19a1d.jpg)
地公審核後填寫的欄位
- 中高污染（Y/N/null）
- new factory（Y/N/null）
- Are we going to report? (Y/N/pending)
- reviewer
- if N/pending: reason(note), auto-tag -> frontend

![01 審核回報3](https://user-images.githubusercontent.com/60970217/82997105-864c9500-a038-11ea-8f5f-1c34a3253507.jpg)
審核時希望是一頁式

2.下載公文
![02下載公文](https://user-images.githubusercontent.com/60970217/82997108-877dc200-a038-11ea-9e68-fa1d4c76d55c.jpg)
可參考 #283 

3.追蹤公文
![03 追蹤公文](https://user-images.githubusercontent.com/60970217/82997112-88165880-a038-11ea-8b04-8f857d4873b1.jpg)
目前整理的[舉報狀態](https://docs.google.com/spreadsheets/d/1Fk9jO6wICKDbwU8vBJXwt7TT1UYFEG5t8IiylqkWcNY/edit#gid=1560937202)
政府回應可粗分成下列狀態
![舉報狀態 3](https://user-images.githubusercontent.com/60970217/82997917-99139980-a039-11ea-8b38-c3ee54257fb7.jpg)

**Comment by aelcenganda** [comment]
@deeper747 請你在這邊幫我補上 draw.io 上的流程圖

**Comment by aelcenganda** [comment]
現在最接近現狀的 spec 是 #389
