### ISSUE TITLE
django下載csv失敗

### ISSUE THREAD

**Issue by deeper747** [Disfactory/Disfactory#318]
**Describe the bug**
在後台勾了62間工廠後，選擇「輸出成csv檔」，點下「go」，跑出錯誤頁面。
試了20間工廠亦同。
<img width="1263" alt="截圖 2020-06-09 上午10 44 05" src="https://user-images.githubusercontent.com/60970217/84127643-1c89ad80-aa72-11ea-99de-8799b168e1a1.png">

**To Reproduce**
同上

**Screenshots**
點進上面截圖中的switch to copy-and-paste view後的文字：
> Environment:
> 
> 
> Request Method: POST
> Request URL: https://api.disfactory.tw/admin/api/factory/
> 
> Django Version: 2.2.10
> Python Version: 3.7.5
> Installed Applications:
> ['django.contrib.admin',
>  'django.contrib.auth',
>  'django.contrib.contenttypes',
>  'django.contrib.sessions',
>  'django.contrib.messages',
>  'django.contrib.staticfiles',
>  'django.contrib.gis',
>  'rest_framework',
>  'corsheaders',
>  'django_q',
>  'django_db_logger',
>  'users.apps.UsersConfig',
>  'api.apps.ApiConfig']
> Installed Middleware:
> ['corsheaders.middleware.CorsMiddleware',
>  'django.middleware.security.SecurityMiddleware',
>  'django.contrib.sessions.middleware.SessionMiddleware',
>  'django.middleware.common.CommonMiddleware',
>  'django.middleware.csrf.CsrfViewMiddleware',
>  'django.contrib.auth.middleware.AuthenticationMiddleware',
>  'django.contrib.messages.middleware.MessageMiddleware',
>  'django.middleware.clickjacking.XFrameOptionsMiddleware']
> 
> 
> 
> Traceback:
> 
> File "/root/.local/share/virtualenvs/backend-6x8oTjDG/lib/python3.7/site-packages/django/core/handlers/exception.py" in inner
>   34.             response = get_response(request)
> 
> File "/root/.local/share/virtualenvs/backend-6x8oTjDG/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
>   115.                 response = self.process_exception_by_middleware(e, request)
> 
> File "/root/.local/share/virtualenvs/backend-6x8oTjDG/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
>   113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)
> 
> File "/root/.local/share/virtualenvs/backend-6x8oTjDG/lib/python3.7/site-packages/django/contrib/admin/options.py" in wrapper
>   606.                 return self.admin_site.admin_view(view)(*args, **kwargs)
> 
> File "/root/.local/share/virtualenvs/backend-6x8oTjDG/lib/python3.7/site-packages/django/utils/decorators.py" in _wrapped_view
>   142.                     response = view_func(request, *args, **kwargs)
> 
> File "/root/.local/share/virtualenvs/backend-6x8oTjDG/lib/python3.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
>   44.         response = view_func(request, *args, **kwargs)
> 
> File "/root/.local/share/virtualenvs/backend-6x8oTjDG/lib/python3.7/site-packages/django/contrib/admin/sites.py" in inner
>   223.             return view(request, *args, **kwargs)
> 
> File "/root/.local/share/virtualenvs/backend-6x8oTjDG/lib/python3.7/site-packages/django/utils/decorators.py" in _wrapper
>   45.         return bound_method(*args, **kwargs)
> 
> File "/root/.local/share/virtualenvs/backend-6x8oTjDG/lib/python3.7/site-packages/django/utils/decorators.py" in _wrapped_view
>   142.                     response = view_func(request, *args, **kwargs)
> 
> File "/root/.local/share/virtualenvs/backend-6x8oTjDG/lib/python3.7/site-packages/django/contrib/admin/options.py" in changelist_view
>   1711.                 response = self.response_action(request, queryset=cl.get_queryset(request))
> 
> File "/root/.local/share/virtualenvs/backend-6x8oTjDG/lib/python3.7/site-packages/django/contrib/admin/options.py" in response_action
>   1397.             response = func(self, request, queryset)
> 
> File "/root/Disfactory/backend/api/admin/mixins.py" in export_as_csv
>   18.             writer.writerow([getattr(obj, field) for field in field_names])
> 
> File "/root/Disfactory/backend/api/admin/mixins.py" in <listcomp>
>   18.             writer.writerow([getattr(obj, field) for field in field_names])
> 
> Exception Type: AttributeError at /admin/api/factory/
> Exception Value: 'Factory' object has no attribute 'get_name'

**Desktop (please complete the following information):**
 - MacOS 10.15.5
 - chrome ver. 83.0.4103.97

**Comment by stegben** [comment]
should be resolved via c705d96, please check again

**Comment by deeper747** [comment]
fix checked, tks!
