### ISSUE TITLE
[Admin] 一鍵下載包含多份公文的文件

### ISSUE THREAD

**Issue by darrenjhsu** [Disfactory/Disfactory#323]
**Is your feature request related to a problem? Please describe.**
地公過去生成公文要從一份 csv 總表一個一個複製到公文 template 上，很累 (ref. #283)

**Describe the solution you'd like**

- [x] 前端 action 「下載公文」

- [x] Main function: 接受 N 個包有公文資訊的 object （流水號、工廠、受文者、內容、照片網址 etc.），產生包含有 N 份公文的一個 docx 檔案。object 的內容取決於勾選了哪些要舉報的工廠。

- [x] 決定公文檔名的 pattern

**Describe alternatives you've considered**

不是很確定 odf 跟 docx 之間有沒有一定要用哪個，不過 odfpy 的 documentation 做得不是很好，所以偏好使用 python-docx. 

**Additional context**

1. 用 python-docx 實作了一下，發現[公文範例](https://drive.google.com/file/d/11nLXFXjKA3HWdYsrisi0hn7hORrt8o8q/view?usp=sharing)裡面比較複雜的 element 是「正本」和「裝訂線」，在 python-docx 裡面沒有簡單可以相對應的 API

2. 於是用一份含有「正本」跟「裝訂線」的空白文件當 template, 加入文字和圖可以產生與公文範例相同的格式

3. 多份文件可以[組合成一份](https://stackoverflow.com/questions/61221770/combine-word-files-with-python-docx-and-add-page-breaks)然後存最後合併的檔案

4. 用 Microsoft Word 打開合併的檔案時會有檔案有部分 unreadable 的警告，但是自動修復後不影響內容

![image](https://user-images.githubusercontent.com/31137770/84461230-8e5c2580-ac31-11ea-909a-e30a8effed8e.png)

**Comment by aelcenganda** [comment]
@deeper747 @Swind 幫我看一下這個 issue 能不能關掉了？

**Comment by deeper747** [comment]
@stegben 這個功能 我在staging上測試OK了！ 要請你幫忙deploy到正式的後台上～

**Comment by Swind** [comment]
目前這個功能已經完成了，之後會等 document 頁面好了之後再遷移過去，這部分應該會寫在另外一個 Issue 上面。
所以麻煩你幫我關掉了
Thanks

**Comment by stegben** [comment]
已佈署上 production

**Comment by stegben** [comment]
python-docx 的 add_picture 會有 `docx.image.exceptions.UnrecognizedImageError` 在底下這張圖
https://i.imgur.com/Q3fplPG.jpg

**Comment by Swind** [comment]
> python-docx 的 add_picture 會有 `docx.image.exceptions.UnrecognizedImageError` 在底下這張圖
> https://i.imgur.com/Q3fplPG.jpg

Orz  我現在來查查，感謝

**Comment by stegben** [comment]
我這邊也試著看看這個問題

**Comment by stegben** [comment]
重製這個 bug:

```
$ python manage.py shell
```

```python
from api.admin.actions.export_docx import new_document
doc = new_document()
from urllib.request import urlopen
data = urlopen("https://i.imgur.com/Q3fplPG.jpg").read()
from io import BytesIO
doc.add_picture(BytesIO(data))
```

**Comment by stegben** [comment]
發現用 PIL 先把 data 存到系統，再讀一次就可以成功：

```
from urllib.request import urlopen
from io import BytesIO
from PIL import Image
from api.admin.actions.export_docx import new_document

TMP_FNAME = "/tmp/test_image.jpg"
doc = new_document()
data = urlopen("https://i.imgur.com/Q3fplPG.jpg").read()
img = Image.open(BytesIO(data))
img.save(TMP_FNAME)

with open("/tmp/test_image.jpg", 'rb') as f_img:
    doc.add_picture(f_img)
```

**Comment by Swind** [comment]
主要原因是 python-docx 的這個陳年老 Bug，他對於一些 jpg 檔案的解析有問題

https://github.com/python-openxml/python-docx/issues/187

我等等會上一個 workaround，我看到我們有安裝 PIL。
所以我會先將所有圖片轉成 PNG 之後在放到 docx 裡面

**Comment by Swind** [comment]
> 發現用 PIL 先把 data 存到系統，再讀一次就可以成功：
> 
> ```python
> from urllib.request import urlopen
> from io import BytesIO
> from PIL import Image
> from api.admin.actions.export_docx import new_document
> 
> TMP_FNAME = "/tmp/test_image.jpg"
> doc = new_document()
> data = urlopen("https://i.imgur.com/Q3fplPG.jpg").read()
> img = Image.open(BytesIO(data))
> img.save(TMP_FNAME)
> 
> with open("/tmp/test_image.jpg", 'rb') as f_img:
>     doc.add_picture(f_img)
> ```
> 
> 但還沒確認這個方法輸出的照片是正確的， @Swind 不曉得這樣會不會有什麼潛在的問題

XDD 我剛剛才看到你這個，我想這樣也是可以的。
主要應該就是 `python-docx` 對 jpg 格式的支援有問題 （他圖片解析處理那部份都是自己寫的）
用 PIL 轉一次讓他可以處理應該是沒問題的，我想想用哪種方式好

**Comment by stegben** [comment]
轉 png 好了。而且我這個方法還要走一次硬碟，看你有沒有辦法 in-memory 轉 png

**Comment by Swind** [comment]
可以，我剛剛測試好了 XDD 
如果全部轉 PNG 轉一張圖片需要 3 秒。
如果只是 jpeg 重新儲存一次只要 0.5 秒，哈哈。所以你那樣做比較好。

在 memory 裡面轉的方法類似這樣，我等等加些 testcase 上個 code

```python
            # Convert all jpeg files to png to workaround python-docx bug
            # https://github.com/python-openxml/python-docx/issues/187
            image_data = PIL.Image.open(BytesIO(data))
            tmp_image_data = image_data

            if image_data.format == "JPEG":
                tmp_image_data = BytesIO()
                image_data.save(tmp_image_data, format="jpeg")

```

**Comment by deeper747** [comment]
公文檔名的 pattern，請從178開始～～～ 
（我是編 109XXX，但我知道 @LittleWhiteYA 怕太快到999，幫我弄了四位數（109XXXX））
