### ISSUE TITLE
「切換不同地圖」鈕未顯示使用者正在看哪圖

### ISSUE THREAD

**Issue by jidanni** [Disfactory/Disfactory#325]
此「切換不同地圖」鈕
![16190-1](https://user-images.githubusercontent.com/1230959/84601678-a8596a80-aeb4-11ea-9c66-27cbc8ef55e9.jpg)
「很不民主」。
切來切去幾個不明圖層。
使用者無法選擇，有無法知道每圖層是什麼（名字）的圖層。

**Comment by Yukaii** [comment]
![disfactory-change-map-layer](https://user-images.githubusercontent.com/4230968/109006657-452c0300-76e6-11eb-9afc-60dcb447d5ab.gif)

已在 2.0 版 UI 實作
