### ISSUE TITLE
UI: users forgot to submit a new factory after successfully upload images

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#334]
**Describe the bug**
使用者常常上傳完照片後沒有成功新增工廠或更新，所收到的 389 張照片中，有 59 張我們無法對應到是哪間工廠，因為使用者沒有送出新增工廠的表單。

我們現在是上傳照片之後會說上傳照片成功，但是那只有上傳照片成功，還沒有把照片加上工廠地理位置傳到我們的資料庫裡。

**To Reproduce**
1. Go to '新增工廠'
2. 選定地點後，進入新增工廠編輯頁面
3. 點選上傳照片，從手機上傳照片後，顯現「上傳成功」 success message
4. 然後使用者就忘記要「送出」新增工廠的表單了

**Expected behavior**
困擾產品經理的是，有些使用者是上傳了高品質他很想舉報的工廠照片，但他沒有送出新增工廠表單，我們就沒有該工廠的地理位置，我們就沒辦法幫他舉報。是使用者沒有意識到他尚未完成新增工廠這整件事，他以為照片上傳成功就成功了，他甚至可能直接把網頁關掉，而不是按退出。我需要的是使用者知道這只是上傳照片完成而已，還有一個步驟，或是我前端設計上應該要直接上傳照片的時候去紀錄是哪個工廠？或是上傳照片完成後，系統自動新增工廠，然後跳轉補充工廠資訊頁面？因為現在上傳完照片後，送出按鈕在超下面的，也可以「送出」按鈕做成一直在最下面浮動的樣子

**Screenshots**

**Additional context**

**Comment by aelcenganda** [comment]
在 Slack 上的討論：

J：
好啊，我可以這週來解決這個問題，我整理一次看是不是這個意思：
現在遇到的問題是：使用者新增工廠的時候，在選擇地點之後進到填寫詳細資訊的頁面，這時候使用者新增照片成功之後卻沒有送出原先的表單的話，就會出現有照片卻沒有工廠資訊的狀況
我目前想到的快速解決方案是另外做一個提醒，提示使用者還沒填寫/送出工廠資訊，確認是不是要離開這個流程/頁面。 使用者確認要離開的話，就... 把他剛上傳的照片從資料庫裡刪掉
另外，現在有beta版可以試跑新增工廠資訊跟照片的流程嗎？（想測試各種不同的use case）

ael  1 day ago
@J 開發版是在 https://dev.disfactory.tw
@J 其實不需要把照片刪掉，就算使用者要離開。

J  1 day ago
我在figma裡面（6/15/2020 Upload Image UX Fix）把UI畫好了，可以找到兩種版本 "Quick Fix"跟"Update UX (For 2.0)"
Quick Fix 版本是改目前現有的UI，統一使用者期待跟按鈕的行為，figma裡面有更詳細的notes
2.0版本包含了更多可能比較少遇見的Use Case，例如移除/新增照片、上傳完照片之後決定編輯地圖等等，我可以這週三再詳細解釋一下
有空的話可以先看一下～
（ @SL 也tag你 哈哈）

**Comment by aelcenganda** [comment]
幫補 Figma 設計圖連結：
https://www.figma.com/file/nTYqE10obqYSy2x9zY6Oer/Disfactory_UI_design?node-id=342%3A1

我覺得 Quick fix 的問題是，完全沒有解決使用者的問題。使用者不是因為要移除照片才退出，而是以為上傳照片成功就代表新增工廠回報成功，滿心歡喜自己成功回報而直接離開頁面，沒有看到「確認送出」的按鈕，但我們資料庫地理位置是空的，完全沒辦法幫他舉報。我要的是使用者知道「上傳照片」 success message 之後還要再按下「確認送出」看到 success message 才確實完成回報，或是簡化這分開又感覺重複的兩個步驟讓使用上很直覺，重點不是讓使用者去移除照片。所以我個人覺得比較好的處理方式，是你上面提到的在上傳照片的 success message 中提醒使用者還要再去送出表單才是回報成功，但在 Figma 裡我沒看到那一頁。

Update UX (For 2.0) 則需要再跟前端 @Yukaii @yoyo930021 確認一下這樣開發上順不順。我比較喜歡這一版，因為我覺得明確的三步驟三頁，有解決到這個問題。但改動這個步驟，就要連補充工廠資訊頁面中的上傳工廠照片頁面一起改，因為目前應該是用同一個模組處理。

**Comment by JennyLan** [comment]
Quick Fix 是按照現有的流程做最小幅度的更動，可以最快推出的解決方案。我認為可以做為2.0版本開發完成之前的解決方案，2.0版本絕對是更好的解決方案。

Quick Fix 更改的地方在：
1. 上傳照片的modal裡面，按鈕下方新增提示訊息。
2. 把“確認送出”的按鈕釘在下方，使用者隨時可以看見。
3. 在照片上傳前“確認送出”按鈕是disable狀態，照片上傳完成之後enable。使用者比較容易注意到按鈕有區別，會直覺性的知道下一步要按“確認送出”。

當然Quick Fix的問題很多，我們今天是假設使用者上傳照片不小心沒送出表單，但是有可能發生的use case也包含：
- 使用者上傳照片之後發現地點選錯了，想回到上一步更新地點
- 使用者不小心上傳到錯的照片，不知道怎麼移除照片所以回到上一步重跑流程
- 使用者新增完一張照片，之後要再新增其他張，但卻一直覆蓋掉原本的照片（我測試的結果是會把原本的照片覆蓋掉）

最大的問題在於，使用者在點下“上傳照片”這個按鍵的時候，不應該期待照片已經傳給地公（照片確實也不應該在這時候傳給地公）。但現在的流程（跟Quick Fix）會讓一部分使用者誤以為上傳完照片就完成舉報，也會有一部分使用者不知道自己上傳的照片已經傳送到地公那邊，覺得還可以編輯，編輯完才傳送。

2.0版本解決了上面提到的所有問題，但是當然就像你說的變動比較多，比較花時間。

**Comment by aelcenganda** [comment]
- 決定用 2.0 三步驟
- 要順便一起改補充工廠的新增照片流程
- 「確認送出」在沒有上片上傳的狀況下 disabled state + error message

**Comment by aelcenganda** [comment]
新版 UI 有試圖解決這個問題，先關掉，之後使用者測試有問題再說

https://www.figma.com/file/nTYqE10obqYSy2x9zY6Oer/Disfactory_UI_design?node-id=342%3A1
