### ISSUE TITLE
在dev版上上傳失敗

### ISSUE THREAD

**Issue by deeper747** [Disfactory/Disfactory#335]
**Describe the bug**
1.上傳的時候卡在「上傳中」的位置
2.照片結束「上傳中」的狀態，但回到地圖卻發現沒有上傳

**To Reproduce**
1. click on '我要新增可疑工廠'
2. click on '新增'
3. choose a picture
4. click on '上傳'
5. See error

**Expected behavior**
smoothly upload the picture

**Screenshots**
狀況一：
<img width="923" alt="截圖 2020-06-17 下午1 42 49" src="https://user-images.githubusercontent.com/60970217/84859993-d13e5300-b0a0-11ea-905d-bd23329f1736.png">
狀況二：
<img width="1280" alt="截圖 2020-06-17 下午1 42 07" src="https://user-images.githubusercontent.com/60970217/84861404-88d46480-b0a3-11ea-8ea9-b3b1fb7ca27a.png">

<img width="892" alt="截圖 2020-06-17 下午2 02 23" src="https://user-images.githubusercontent.com/60970217/84861351-65a9b500-b0a3-11ea-972e-712c47259c6c.png">
<img width="897" alt="截圖 2020-06-17 下午2 02 34" src="https://user-images.githubusercontent.com/60970217/84861358-6a6e6900-b0a3-11ea-88af-f5d79166b1ed.png">

**Desktop (please complete the following information):**
狀況一 
- MacOS
- 10.15.3
 - safari
 - Version 13.0.5

狀況二：
- MacOS
- 10.15.3
- Chrome
- Version 83.0.4103.97

**Additional context**

**Comment by Yukaii** [comment]
用 iOS simulator  13.2 可以重現，on change 事件有成功綁上，但選擇完圖片後無法觸發

![Screen Shot 2020-07-01 at 8 46 54 PM](https://user-images.githubusercontent.com/4230968/86247928-c080f780-bbdf-11ea-8483-995475351080.png)

**Comment by yoyo930021** [comment]
嗚嗚 很難修

**Comment by aelcenganda** [comment]
related to #351 #355 

最後解決方法很爛，就是跳通知提醒使用者要升級系統。這後續可能要再 tracking 一下有沒有改善使用者體驗。
