### ISSUE TITLE
diafactory.tw新增可疑工廠失敗

### ISSUE THREAD

**Issue by deeper747** [Disfactory/Disfactory#336]
**Describe the bug**
使用者回覆無法上傳照片
case1：「我今天要新增可疑工廠，可是上傳照片(僅88K)後一直停留在"上傳中"的狀態，試了不同電腦也是一樣，你們也有一樣的狀況嗎?」
case2：「你好，我在違章工廠回報欲上傳照片但是一直顯示上傳中很長一段時間無法成功上傳，請修復」

**To Reproduce**
1. Go to 'disfactory.tw'
2. Click on '我要新增可疑工廠'
3. Click on '新增'
4. 選擇一張照片
5. Click on '上傳'
6. see error

**Expected behavior**
smoothly upload

**Desktop (please complete the following information):**
case1：
 - win7, win 10
 - chrome
 - 83.0.4103.61

case2：
未知

**Comment by yoyo930021** [comment]
我今天直接看你的電腦來試試

**Comment by aelcenganda** [comment]
建立 CI/CD 追蹤在 #373 #346
