### ISSUE TITLE
[Admin][1-2-1] 調整 factory detail_veiw 顯示欄位

### ISSUE THREAD

**Issue by TobyOoO** [Disfactory/Disfactory#337]
**Is your feature request related to a problem? Please describe.**
顯示審查相關的工廠資訊欄位，以便地公進行審查。

**Describe the solution you'd like**
根據以下記載的規格調整顯示欄位。

**factory info**
此工廠的基本資料
- 工廠編號 (factory.factory_number) #224)
- 工廠 id (factory.id)
- 審查狀態 （篩選）(cet_review_status)
- 檢舉狀態（篩選）cet_report_status）
- 政府回應狀態（gov_reply_summary）多選（自動產生，對應到 `doc_io`）
- 審查人
- 公文負責人

**image 照片區**
- 照片 (preview multiple photos) (image.image_path) 
- 照片上傳者的資訊 (report_record.contact)
- 此工廠地點在2016.5.20的空照圖（google earth） (serializer representation lng, lat) => 含經緯度跟時間標記的 link

**Detail**
合併顯示：
- 行政區（factory.townname）
- 段名 (factory.sectname)
- 段號 (factory.sectcode)
- 地號 (factory.landcode)

經緯度（小地圖 preview）
- lng (factory.lng)
- lat (factory.lng)

細部資訊
- 工廠描述(report_record.others)
- 工廠類型 (factory.factory_type)
- 工廠外部文字 (factory.name)
- 創建時間(factory.created_at)
- 最後更新時間 (factory.updated_at)
- 舉報文號(new table cet_doc_number)

ReportRecords

**Comment by yellowsoar** [comment]
參考： `ModelAdmin.list_display()`
https://docs.djangoproject.com/en/3.0/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_display

**Comment by deeper747** [comment]
希望可以把現在google map的preview變成向document表格裡的「Google Map 連結」！
<img width="719" alt="截圖 2020-11-17 上午9 42 48" src="https://user-images.githubusercontent.com/60970217/99329465-4369cc80-28b9-11eb-86c2-87fe8da6197a.png">

**Comment by deeper747** [comment]
開成了新issue #436
