### ISSUE TITLE
[Admin][1-2-2] 新增審核紀錄

### ISSUE THREAD

**Issue by TobyOoO** [Disfactory/Disfactory#338]
**Is your feature request related to a problem? Please describe.**
提供地公根據工廠 detail_view 新增或修改對應的審核紀錄。

**Describe the solution you'd like**
（這邊可能會需要彈出一個新的視窗）
根據文件的規格製作新增欄位與 Admin 介面。
https://docs.google.com/document/d/1uBqD_Ms1-HHAH1B1SCagsVZS_XKMxYDFuQHOHxkJ4_8/edit#

**Comment by yellowsoar** [comment]
參考： `ModelAdmin.list_display()`
https://docs.djangoproject.com/en/3.0/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_display

**Comment by deeper747** [comment]
@TobyOoO 這個issue是不是後來有被其他issue滿足啊？現在已經可以修改審核狀態了。
<img width="327" alt="截圖 2020-09-10 下午12 03 05" src="https://user-images.githubusercontent.com/60970217/92680513-98d7a980-f35d-11ea-94c3-48ebad2ca3f0.png">
還是說這個issue有其他的意義？

**Comment by aelcenganda** [comment]
就是 `cet_review_status`
