### ISSUE TITLE
Server management

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#349]
**Is your feature request related to a problem? Please describe.**
Using personal server instead of CET's server
- Access control
- Limited contribution time of cph

**Possible choices**
1. Personal server and open access to more than one person => stick to this plan
2. Migrate to CET's own server (But we need to talk to Netivism first)
3. another person to host the server

**To do**
- [ ] Budget support from CET @deeper747 please set up funding procedure

**Comment by aelcenganda** [comment]
升級成 Team (卡在 payment QQ)
然後要開權限去做 staging CD https://github.com/Disfactory/Disfactory/issues/373

**Comment by aelcenganda** [comment]
可能要先開權限

**Comment by stegben** [comment]
目前 server 已經搬移到 CET 的 DigitalOcean 組織帳號，關於登入權限，已跟 @deeper747 有初步討論
