### ISSUE TITLE
where is the "lat" and "lng" column in api.factory.csv

### ISSUE THREAD

**Issue by deeper747** [Disfactory/Disfactory#362]
**Describe the bug**
I couldn't find the  "lat" and "lng" column in new api.factory.csv that I exported today.

**To Reproduce**
export a csv in the factory page

**Expected behavior**
see the lng and lat as they were in older csv files.

**Screenshots**
csv exported at 20200427
<img width="1280" alt="截圖 2020-07-21 上午9 36 03" src="https://user-images.githubusercontent.com/60970217/88002853-13423500-cb36-11ea-8573-5dbde0baab44.png">

csv exported yesterday
<img width="1280" alt="截圖 2020-07-21 上午9 39 05" src="https://user-images.githubusercontent.com/60970217/88002864-1806e900-cb36-11ea-9f5b-f8d5d47fb9aa.png">

**Comment by aelcenganda** [comment]
@deeper747 Is it fixed in https://github.com/Disfactory/Disfactory/pull/367? Please close this issue along with #348 if it is fixed.
