### ISSUE TITLE
Open API 實作

### ISSUE THREAD

**Issue by yellowsoar** [Disfactory/Disfactory#384]
# 實作結果
會有一個 open api 的 endpoint
以及預計會使用 `drf-yasg` 產生
(給開發人員看)的線上 swagger 與 redoc 頁面

drf-yasg package:
https://pypi.org/project/drf-yasg/

swagger demo:
https://drf-yasg-demo.herokuapp.com/cached/swagger/
redoc demo:
https://drf-yasg-demo.herokuapp.com/cached/redoc/

---

# 待決定項目

- endpoint
目前給前端用的 endpoint 是：
https://api.disfactory.tw/api/
需要決定 open api 的 endpoint ，例如：
https://api.disfactory.tw/open/
https://api.disfactory.tw/openapi/
https://api.disfactory.tw/api-open/
https://api.disfactory.tw/open-api/

- 表列：
    - 每個 api 與後列項目
    - 各 api 要回應哪些資料？
    - 各 api 用什麼 http request method？
    - 各 api 需要什麼 query string？
    - 各 api 

例如：
- 工廠列表的 api ，
https://api.disfactory.tw/open/factories
透過 get 訪問，
會回應 `id`, `lat`, `lng`, `landcode`, `towncode`, `townname`, ....
- 隨機取得一個工廠的 api
https://api.disfactory.tw/open/random_factory
- 隨機取得100個工廠的 api：
https://api.disfactory.tw/open/random_factory?amount=100

(實作上可以透過 django rest framework 的 serializer 達成)

- 是否做權限控管
透過：
    - 帳號密碼
    - token
    - CORS (針對 ajax)

**Comment by aelcenganda** [comment]
做好之後，會再丟給技術社群和寫在技術文件裡

**Comment by aelcenganda** [comment]
@Swind 可以麻煩你把 OpenAPI 的連結放在這裡和 repo 的 README 嗎？等我們加入 about page 後我會關掉這個 issue

**Comment by aelcenganda** [comment]
感謝 @Swind 已經做好 OpenAPI 也放到網頁上了

https://api.disfactory.tw/redoc/
