### ISSUE TITLE
Document (List View) 

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#386]
- `id`
- `factory_id`
- `created_at`: [sort]
- `last_updated`：[sort] 
- `cet_staff`
- `cet_report_status`: [filter] 
- `cet_next`： [filter] 
- `gov_response_status`: 
- `display_status`:[filter] 
- 縣市 [filter]
- 鄉鎮區 [filter]
- 政府承辦人 [filter]

(`display_status` 的 `updated_at` 還是要記唷，要傳給前端的 API)

**Comment by deeper747** [comment]
目前已用「鄉鎮市」搜尋取代「承辦」欄位。
未來等承辦的資料累積更多，再開個新issue來把他們放上去，先把這個關掉囉！
