### ISSUE TITLE
有資訊但沒照片的新增點位

### ISSUE THREAD

**Issue by deeper747** [Disfactory/Disfactory#392]
**Describe the bug**
出現了只有資訊但沒有照片的新增點位

**To Reproduce**
https://disfactory.tw/#map=17.00/120.6809347/24.272856620000013

**Expected behavior**
我只是想知道為什麼會有這個情況😅
照理說照片應是必填資訊？

**screenshot**
<img width="1280" alt="截圖 2020-09-11 下午5 26 40" src="https://user-images.githubusercontent.com/60970217/92905190-0a931e80-f456-11ea-97a3-78eb28ed7051.png">
<img width="1280" alt="截圖 2020-09-11 下午5 26 47" src="https://user-images.githubusercontent.com/60970217/92905212-0ebf3c00-f456-11ea-9de9-9d788f4968c2.png">
<img width="1280" alt="截圖 2020-09-11 下午5 26 55" src="https://user-images.githubusercontent.com/60970217/92905215-0f57d280-f456-11ea-91e0-a749d76fa84c.png">

**Comment by aelcenganda** [comment]
@deeper747 可以去後台看一下工廠 ID，然後私訊 id 給前端和後端看一下是發生什麼事了嗎？
