### ISSUE TITLE
給使用者看的工廠回報進度 `display_status` 類別

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#397]
後台介面：單選下拉式選單
不會頻繁變動，可能幾個月才會改一次。

再請 @deeper747 幫忙給有哪幾個文字的狀態囉！

**Comment by deeper747** [comment]
"已檢舉"
"已排程稽查"
"陳述意見期"
"已勒令停工"
"已發函斷電"
"已排程拆除"
"不再追蹤"

前端顯示給使用者時，希望在上方加註「此狀態以地方政府經發單位進度為主」。

**Comment by aelcenganda** [comment]
@deeper747 為什麼沒有 `已拆除` ？

不再追蹤應該有很多原因吧

**Comment by noobOriented** [comment]
以上問題有共識了嗎？
我這邊已經好了，可以立刻修改

**Comment by deeper747** [comment]
改好了！

**Comment by noobOriented** [comment]
我這邊也好囉
