### ISSUE TITLE
無法新增點位

### ISSUE THREAD

**Issue by deeper747** [Disfactory/Disfactory#398]
**Describe the bug**
上傳照片正常，但點了送出之後，pin沒有出現在地圖上

**To Reproduce**
1.新增可疑工廠
2.上傳照片（成功）
3.按下送出

**Expected behavior**
pin正常出現

**Screenshots**
有人透過問題表單反映，我剛剛用筆電+chrome測試上傳也不行
<img width="342" alt="截圖 2020-09-17 上午10 01 33" src="https://user-images.githubusercontent.com/60970217/93411171-1efb6f00-f8cd-11ea-9ac2-dd968ba3c95a.png">

**Comment by aelcenganda** [comment]
我用 Firefox 80.0.1 desktop 版也無法成功新增點位，在 production 和 dev 都不行

以下是 error message

`Error: [vue-composition-api] "onUnmounted" get called outside of "setup()"
    f vue-composition-api.module.js:32
    x vue-composition-api.module.js:79
    ht vue-composition-api.module.js:746
    qt useBackPressed.ts:14
    P Map.vue:340
    VueJS 4
    get vue-composition-api.module.js:706
    a AppButton.vue:44
    VueJS 3
vue.runtime.esm.js:1888:12
XHRPOSThttps://staging.disfactory.tw/api/factories
[HTTP/2 400 Bad Request 242ms]

Error: Request failed with status code 400
    exports createError.js:16
    exports settle.js:17
    onreadystatechange xhr.js:59
    exports xhr.js:34
    exports xhr.js:11
    exports dispatchRequest.js:59
    promise callback*0a06/c.prototype.request Axios.js:53
    t Axios.js:78
    exports bind.js:9
    Vt index.ts:117
    i tslib.es6.js:73
    i tslib.es6.js:69
    Vt app.efaf7747.js:1
    submitFactory FormPage.vue:440
    i tslib.es6.js:73
    i tslib.es6.js:69
    submitFactory app.efaf7747.js:1
    click FormPage.vue:1
    VueJS 4
    get vue-composition-api.module.js:706
    a AppButton.vue:44
    VueJS 33
index.ts:121:12
TypeError: t.setCreateFactorySuccessModal is not a function
    submitFactory FormPage.vue:454
    s tslib.es6.js:71
    promise callback*c tslib.es6.js:72
    i tslib.es6.js:73
    i tslib.es6.js:69
    submitFactory app.efaf7747.js:1
    click FormPage.vue:1
    VueJS 4
    get vue-composition-api.module.js:706
    a AppButton.vue:44
    VueJS 33`

**Comment by Yukaii** [comment]
改變行為的 commit: https://github.com/Disfactory/Disfactory/commit/5d62f1785cd83a7c63a126b4a984e8f34bdeb967#diff-fb36a04053b51badba99fc2aea0abf29R89

前端未選擇類型的時候會送 '0'，若不填送出後端目前會回 `This field is required.`，因為工廠類型欄位非必填，這邊後端行為會需要修改
