### ISSUE TITLE
Delete Factory on admin page: required to delete report records separately

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#403]
**Describe the bug**
Want to delete a single factory but is required to delete each report record separately. Not convenient .

**Expected behavior**
one single button/action to soft delete a factory with double confirmation

**Screenshots**
![螢幕快照 2020-09-23 下午9 19 12](https://user-images.githubusercontent.com/9480974/94017829-75dbd980-fde2-11ea-963d-531d22c2d1ec.png)

**Comment by stegben** [comment]
@LittleWhiteYA 請問這個能請你協助嘛？

**Comment by LittleWhiteYA** [comment]
這ㄍ研究了一下有點難做
我的理解是好像要變成 inject javascript，django 好像沒支援刪除關聯的 table rows？

**Comment by aelcenganda** [comment]
@stegben @LittleWhiteYA 那可以先給你們是哪些工廠是測試亂貼的，然後你們從 DB 刪嗎？因為這次 g0v 年會在台南，那些亂新增的點很多也是在台南

**Comment by aelcenganda** [comment]
目標：是前端不會拿到要刪除的工廠資料
問題：系統預設沒有先刪除每一筆相關聯 ReportRecord 的話，沒有辦法刪除 factory
