### ISSUE TITLE
Display_status API

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#406]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Yukaii** [comment]
@noobOriented @LittleWhiteYA

1. 列表的 factory API 需要 `display_status` 欄位 (來自最新 document 的 display_status 欄位)
2. 單一 factory 的 API 需要 `display_status` 欄位 (來自最新 document 的 display_status 欄位)

**Comment by aelcenganda** [comment]
@Yukaii 現在是不是改成 `document_display_status` 還是 `doc_display_status`？

**Comment by aelcenganda** [comment]
後端做在 #410 ， @Yukaii 麻煩妳確認後關掉這個 issue

**Comment by Yukaii** [comment]
confirmed
