### ISSUE TITLE
django政府來源工廠的updated time

### ISSUE THREAD

**Issue by deeper747** [Disfactory/Disfactory#407]
**Describe the bug**
現在的 Factory List View 的 updated time 欄位顯示的是記在 Factory table 欄位的更新時間
但是在整理檢舉公文上所需要 sort 的時間是最新有新增圖片、工廠描述的工廠，因此需要拿來排序的是 reportrecord 的最後更新時間。

**Expected behavior**
新增一個以reportrecord 最後更新的時間的欄位
並且希望list view顯示上，上面這個欄位取代現在的 updated time
要可以用這個欄位 sort

也許可以取名 `reportrecord_updated_at` ？

**Comment by LittleWhiteYA** [comment]
所以是期望說現在這個 updated_at 的值不是 `factory.updated_at` ，而是改成根據某個 factory 底下最新的 `reportrecord.updated_at` 的值？

**Comment by deeper747** [comment]
對的！

**Comment by LittleWhiteYA** [comment]
其實不是 `reportrecord.updated_at`
在使用者更新 factory 或 image 的時候都會自動產生 report record，使用者不會主動碰到 report record 每欄的值，所以 report record 其實不會有 updated_at
這個 features 最主要是想知道的是某個 factory 最新被更新的時間，所以應該是 reportrecord 的 created_at 而不是 updated_at
