### ISSUE TITLE
Document: 替 CET 增加用來管理公文進度與狀況的 Tag

### ISSUE THREAD

**Issue by Swind** [Disfactory/Disfactory#411]
## Document: CET 用來管理公文進度與狀況的 Tag

* cet_report_status : CET 內部管理用的進度
* cet_next： CET 下一步要做什麼
* gov_response_status: 可能會有針對四個地方政府單位進度不同的 tag

以上幾個 Tag 都會使用 Many to Many 的 Table 來實做，
讓每個欄位同時都可以多個 Tags，方便 CET 管理。

**Comment by stegben** [comment]
Merfed via #416
