### ISSUE TITLE
UI 2.0 使用教學

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#414]
預計 11/18 code freeze 後，可以來截圖製作。

**Comment by aelcenganda** [comment]
X Lin 把截圖檔案更新在

https://drive.google.com/file/d/1QSKHETniwr18pnOJijDLRMsoJRYVXgWd/view?usp=sharing

**Comment by Xinroo** [comment]
單張使用說明路徑如下:

https://drive.google.com/drive/folders/1S6ZdknjdByuNjQKrIhv3LmAP5rO4dGh1?usp=sharing

**Comment by aelcenganda** [comment]
@Yukaii @yoyo930021 
如果有時間的話先把新的使用教學圖片換上去吧！麻煩你們了
地號的 API 可以晚一點再弄

**Comment by Yukaii** [comment]
Fixed in https://github.com/Disfactory/frontend/commit/3991610fdde24cc54f6ce5969b865666b5b1c560
