### ISSUE TITLE
UI 2.0 User Feedbacks and enhancements

### ISSUE THREAD

**Issue by aelcenganda** [Disfactory/Disfactory#417]
### 希望先做的
- [x] Problem: [我想新增可疑工廠] 有點字太小或不明顯，兩位超過五十歲的測試者需要花超過 20 秒尋找，其中一位需要拿下眼鏡。
![2020-10-28-213540_001](https://user-images.githubusercontent.com/9480974/97443254-cc01e680-1965-11eb-9399-6d860fa45e7d.png)

- [ ] Problem: 新增工廠成功然後回到地圖之後，如果該地點點位附近已經有數個新增的民眾回報工廠，使用者會不知道哪個是自己新增的，無法確認自己是否新增成功。
![2020-10-28-213540_002](https://user-images.githubusercontent.com/9480974/97443484-08cddd80-1966-11eb-94d0-82715f62e3b8.jpeg)
![2020-10-28-213540_003](https://user-images.githubusercontent.com/9480974/97443508-12efdc00-1966-11eb-808c-c875b0da199f.png)

- [ ] Problem: 分享複製連結後，地圖跳回以該工廠為中心的地圖，但是使用者還是不知道是哪間工廠。
possible solutions: 可能需要預先幫忙把該工廠的 bottom sheet 打開，讓使用者看見工廠資訊。或是選取的工廠要 mark？
- [ ] Problem: 在上傳照片的步驟，因為沒有任何的地址或者座標資訊。使用者有疑惑，不知道是否需要補充填入地址，或者座標資訊。
![image (2)](https://user-images.githubusercontent.com/9480974/97442627-05862200-1965-11eb-8a5c-f2741eb35522.png)

### Nice to have
- [ ] Problem: 一開始進入地圖要求同意的頁面，文字和排版可能需要再解釋清楚網站使用目的 @deeper747 
- [ ] Problem: 一個工廠很多照片的話，補充照片因為放在最右側，需要 scroll 才能看到，有使用者誤以為無法新增照片。
- [ ] Problem: 上傳照片上傳中的字樣，如果網路太慢拖太久的話，使用者不確定是當掉還是真的在上傳。
Solutions: 也許可以加動態 loading？
- [ ] Problem: 返回步驟 1/3、2/3 使用者看不太懂

### 待討論
- 新增可疑工廠之後，是不是要 call to action 讓使用者做下一步，例如：再新增一間工廠、去地球公民基金會看月報。 @deeper747 
- 如果使用者對於非農地範圍有疑慮，是否能快速找到我們農地分區的資料來源

**Comment by YUNJENCHIEN** [comment]
新增工廠時，畫面希望可以明確讓使用者知道選擇地點（ex.地址）
還有剛新增完的工廠要比較明顯（比較大或顏色不一樣）
![Uploading 3C28E29E-DF75-4465-A5F0-BB3CF2860587.png…]()

**Comment by YUNJENCHIEN** [comment]
![7C110E9E-04DA-4371-8029-3505A0A07661](https://user-images.githubusercontent.com/63830867/98815248-ccb87380-2461-11eb-84ab-4363c3b3a660.png)

**Comment by deeper747** [comment]
有人不知道「沒有開放手機定位權限」是什麼意思，不知去哪邊打開定位
![Uploading 009AB437-9BAB-4614-B29B-0AB7928070EA.jpeg…]()

**Comment by deeper747** [comment]
點「常見問題」會自動跳轉到landing page的「教學頁面」，而不是「常見問題」

**Comment by YUNJENCHIEN** [comment]
![image](https://user-images.githubusercontent.com/63830867/98829871-acde7b00-2474-11eb-831d-279460533a3c.png)
之前訪問的南投土地仲介有說:在一般的使用錯誤回報資訊中，會包含單位電話(基本客服流程)ex.請撥打本公司客服專線0800-700-365（手機請改撥付費電話04-23542030）回報此問題。但我在想應該可以附上常見問題的超連結來減少打電話的次數。

![image](https://user-images.githubusercontent.com/63830867/98830981-f8455900-2475-11eb-9e2d-ba292a785977.png)

**Comment by deeper747** [comment]
測試者提問：如果想要檢舉工廠的話，如何得知他是105.05.20以後的工廠？
->和之前在臺北大學附近測試、本來沒有檢舉意願的使用者，遇到一樣的問題。

此外，也想要建議日期的話，可以寫105年5月20日。因為剛開始看一直以為是經緯度的小數點。
->這個請設計評估

**Comment by JennyLan** [comment]
我的回覆是粗體字的部分，有些快速的直接改了，在Figma有另外寫notes。

> ### 希望先做的
> * [ ]  Problem: [我想新增可疑工廠] 有點字太小或不明顯，兩位超過五十歲的測試者需要花超過 20 秒尋找，其中一位需要拿下眼鏡。
**字體大小改大了**

> * [ ]  Problem: 新增工廠成功然後回到地圖之後，如果該地點點位附近已經有數個新增的民眾回報工廠，使用者會不知道哪個是自己新增的，無法確認自己是否新增成功。
**新增成功應該要有新增成功的提示訊息出現，可以透過訊息確認新增成功。
使用者需要知道或是記得自己檢舉的工廠在哪嗎？還是只是想確認新增成功？
如果是想記得或是追蹤自己檢舉的工廠，那又是另一個流程了。**

> * [ ]  Problem: 分享複製連結後，地圖跳回以該工廠為中心的地圖，但是使用者還是不知道是哪間工廠。
>   possible solutions: 可能需要預先幫忙把該工廠的 bottom sheet 打開，讓使用者看見工廠資訊。或是選取的工廠要 mark？
**改了工廠座標的Selected State，原先只有座標放大，現在改為放大及顏色加深**

> * [ ]  Problem: 在上傳照片的步驟，因為沒有任何的地址或者座標資訊。使用者有疑惑，不知道是否需要補充填入地址，或者座標資訊。
**在新增工廠的流程中，應該要有三步驟，截圖裡好像沒有？
從header應該要可以看得出來有三步驟，在第二步上傳照片的時候可以回到第一步看，或是到最後一步會顯示所有資訊（包含座標位置，照片，及其他補充資訊）讓使用者確認最後一次在上傳。**

> ### Nice to have
> * [ ]  Problem: 一個工廠很多照片的話，補充照片因為放在最右側，需要 scroll 才能看到，有使用者誤以為無法新增照片。
**放最後面是希望使用者可以看了其他照片覺得需要補充再補充。如果我們希望使用者補充了我們再自己審核，可以把補充照片移到第一格。**

> * [ ]  Problem: 上傳照片上傳中的字樣，如果網路太慢拖太久的話，使用者不確定是當掉還是真的在上傳。
>   Solutions: 也許可以加動態 loading？
**可以新增 “...“ 動畫： "上傳中" -> "上傳中." -> "上傳中.." -> "上傳中..." -> loop
需要mockup再跟我說**

> * [ ]  Problem: 返回步驟 1/3、2/3 使用者看不太懂
**使用者認為是什麼意思？**

**Comment by DoraLyn20** [comment]
做了三個設計上的小更動，[Figma頁面在此](https://www.figma.com/file/dFuJKpdDcmHNDqdj1011Zo/Disfactory_UI_design_2021?node-id=2097%3A8774) (Dev ready 2.2)

- 前端｜讓使用者知道現在正在看哪個PIN → 更改 active pin的外觀（多加一個框）
- 前端｜讓使用者看得出來自己到底是上傳了到哪個PIN → 三天以內（７２小時）有被EDIT過資訊的PIN，上頭加一個「NEW」
- 後端｜讓使用者認知到那個 PIN 還差照片 → 像是「已處理：{詳細狀態}」一樣，「未處理」的詳細狀態也可以分已經有照片或沒有照片兩種狀態。

**Comment by DoraLyn20** [comment]
已將這個issue裡提到的改善點都整理到 frontend 的 issue 那邊了。
