### ISSUE TITLE
document page view 欄位

### ISSUE THREAD

**Issue by deeper747** [Disfactory/Disfactory#444]
**Is your feature request related to a problem? Please describe.**
想要看到包含在公文上的所有資訊

**Describe the solution you'd like**
Tags

- [x] display status

- [x] cet report status

- [x] cet next

- [x] gov response

factory

- [x] 工廠號碼

- [x] 鄉鎮市

- [x] 地段號（sect_name, landcode）

- [ ] 補充描述（others）

- [x] 工廠名稱

- [x] Lat, Lng

- [x] google map連結

- [x] 工廠照片

Follow ups

- [x] 來電

- [x] 公文回函

- [x] 去電

**Describe alternatives you've considered**
有個factory link可以讓我回到factory那邊的後台即可

**Additional context**

**Comment by deeper747** [comment]
others 目前就透過回到factory的連結回去看，下個milestone再嘗試加入

**Comment by aelcenganda** [comment]
@deeper747 你說下個 milestone 再做 `others`，我好像沒有看到相關 issue 欸，可以補上連結過來這裡嗎？
