### ISSUE TITLE
「分享」網址進入後的畫面

### ISSUE THREAD

**Issue by deeper747** [Disfactory/Disfactory#456]
**Is your feature request related to a problem? Please describe.**
從別人分享的連結進入之後，看起來只是進入了回報系統，不知道是哪一個
[問題螢幕錄影](https://cettw-my.sharepoint.com/:v:/g/personal/pisces_cet-taiwan_org/EaHG3YLOjEZLp89MrSw93b4BsNOaTGvNfWtKk4mOD9Amjw?e=Ggh8xa
)

**Describe the solution you'd like**
- [ ] 透過經緯度進入網站之後可以自動展開pin

**Comment by aelcenganda** [comment]
@Yukaii 應該做在這個 issue 上，目前處理方式是把工廠資訊叫出來，pin 就會被擋住

https://github.com/Disfactory/frontend/issues/42
