### ISSUE TITLE
document搜尋需要query段名、公文號

### ISSUE THREAD

**Issue by deeper747** [Disfactory/Disfactory#468]
**Is your feature request related to a problem? Please describe.**
收到公文回函時，有時對方沒有寫是回哪一封、哪個區，有段名才能找到該document進行紀錄

**Describe the solution you'd like**
搜尋功能將sect_name加入要撈的資料庫

**Additional context**
像是這兩張公文回來的時候，我發現難以透過搜尋找到對應的document（因為在檢舉非常多的鄉鎮，單用鄉鎮名會看到七八個結果
<img width="377" alt="截圖 2020-12-25 上午11 43 40" src="https://user-images.githubusercontent.com/60970217/103117688-87b16f00-46a6-11eb-81d1-2f26c8913390.png">
<img width="742" alt="截圖 2020-12-25 上午11 44 01" src="https://user-images.githubusercontent.com/60970217/103117690-8bdd8c80-46a6-11eb-9fcd-ca4d13e09e56.png">

**Comment by aelcenganda** [comment]
所以現在哪些欄位是可以搜尋到的？
