### ISSUE TITLE
DB backup mechanism

### ISSUE THREAD

**Issue by stegben** [Disfactory/Disfactory#48]
定期做備份，可以等部屬環境搞好再來弄

**Comment by stegben** [comment]
先研究一下 middle2 那邊會做怎麼樣的備援，再來決定我們怎麼做

**Comment by aelcenganda** [comment]
ronnywang：
目前 disfactory 的 db 所在的主機是有做每日備份，最多留七天，所以假如發生類似意外是有機會救回來的，但是救援動作可能會需要我人工約四到五個小時處理時間

![螢幕快照 2020-04-02 下午3 09 46](https://user-images.githubusercontent.com/9480974/78220465-2a600700-74f4-11ea-828b-35b9bdb4c587.png)

**Comment by stegben** [comment]
20200408 討論

每天把整份 db 備份下來，存到 google drive 或 rsync 到某個 server。備份保留一段時間即可（兩週到一個月）

**Comment by stegben** [comment]
2020/07/08 discussion with @yellowsoar 

可以在 s3 申請一個空間，寫一個 lambda 來做備份（給一個 ssh key ，bash script 跑 pg_dump），並且掛 CDN 去指到那個 trigger

**Comment by aelcenganda** [comment]
目前會固定每天備份到 staging 。
