### ISSUE TITLE
後端 Query 有嚴重效能問題

### ISSUE THREAD

**Issue by stegben** [Disfactory/Disfactory#484]
目前做 query 都花到好幾秒：
![image](https://user-images.githubusercontent.com/6868283/105175298-ae0be280-5b5e-11eb-8d71-f385f6a8434e.png)

看後台的 htop ，可以發現一直在做 swap 
![image](https://user-images.githubusercontent.com/6868283/105175251-a3514d80-5b5e-11eb-9738-89160fc2b27c.png)

**Comment by stegben** [comment]
看來是我們不小心被值入木馬，已透過這個[連結](https://blog.csdn.net/subfate/article/details/106546646)提供的方式解決

**Comment by stegben** [comment]
速度變快了，但仍不在一個可接受的範圍
![image](https://user-images.githubusercontent.com/6868283/105180728-e236d180-5b65-11eb-85e7-1134f9ceadce.png)

**Comment by LittleWhiteYA** [comment]
哇靠三小   發生什麼事ㄌ
