### ISSUE TITLE
研究與撰寫座標轉地號

### ISSUE THREAD

**Issue by yoyo930021** [Disfactory/Disfactory#5]

**Comment by Loooffy** [comment]
**找到相關的function但不知道如何判斷能不能運用**

我在[地籍圖資網路便民系統](https://easymap.land.moi.gov.tw/R02/Index)有這個服務
輸入WGS84座標後，會給地段和地號，這個應該就是我們需要的功能
![image](https://user-images.githubusercontent.com/7054287/65369770-e73ef480-dc83-11e9-941b-edef6da874ec.png)

我在原始碼追追追，最後找到一個有一個POST方法的function，在想或許可以在後端建一個POST request去抓資料，但第一，不知道怎麼確定POST是否有權限，從這個function中還是不知道該怎麼送一個正確的POST request。

以下是找到這些相關function的路徑。

--

這個查詢功能在[原始碼](https://github.com/Loooffy/references/blob/master/%E5%9C%B0%E7%B1%8D%E5%9C%96%E8%B3%87%E7%B6%B2%E8%B7%AF%E4%BE%BF%E6%B0%91%E7%B3%BB%E7%B5%B1_source)的第309行

```
$("#coord_botton").click(function(){
	var type = $("#select_coordType_id").val();
	var wgs84x, wgs84y ;
	if (type == "WGS84"){
		wgs84x = $("#wgs84xId").val();
		wgs84y = $("#wgs84yId").val();
	}else if (type == "WGS84_DMS"){
		var lonD = $("#wgs84xdId").val();
		var lonM = $("#wgs84xmId").val();
		var lonS = $("#wgs84xsId").val();
		var latD = $("#wgs84ydId").val();
		var latM = $("#wgs84ymId").val();
		var latS = $("#wgs84ysId").val();
		wgs84x =parseFloat(lonD) + parseFloat(lonM)/60 + parseFloat(lonS)/3600;
		wgs84y =parseFloat(latD) + parseFloat(latM)/60 + parseFloat(latS)/3600;
	}else if (type == "TWD97"){
		var twd97x = $("#twd97xId").val();
		var twd97y = $("#twd97yId").val();
		var wgs84pnt = new OpenLayers.LonLat(twd97x,twd97y).transform( proj3826, proj4326);
		wgs84x = wgs84pnt.lon;
		wgs84y = wgs84pnt.lat;
	}	
	//console.log(wgs84x , wgs84y);
	if (wgs84x && wgs84y){
		searchByWGS84Coord(wgs84x , wgs84y) ; 
	}	
});
```

最底下searchByWGS84Coord放在[set_live.js?3.5.4](https://github.com/Loooffy/references/tree/master/js)裡頭第546行
```
function searchByWGS84Coord(wgs84x , wgs84y){
	initStatus(); 
	var tasks = [];
	tasks.push( function(){
		return getPointCity(wgs84x, wgs84y);
	});
	tasks.push( function(taskResult){
		var cityCode = taskResult.cityCode ; 
		return Promise.all([taskResult , getDoorInfoByXY(cityCode , wgs84x, wgs84y) ]);
	});	
	return tasks.reduce(function(promiseChain, currentTask){
	    return promiseChain.then(currentTask );
	}, Promise.resolve([])).then(function(arrayOfResults) {
		var cityCode = arrayOfResults[1].cityCode;
		var townCode = arrayOfResults[1].townCode;
		var office = arrayOfResults[1].office ;
		var sectno = arrayOfResults[1].sectno;
		var landno = arrayOfResults[1].landno ; 
		var sectName = arrayOfResults[1].sectName; 
		if (office && landno && sectno){
			activeLandNo = landno; 
			activeSectNo = sectno;
			getMap(office,sectno,landno,function(){
				//2018-05-02 ��鞉�蹱䰻閰Ｚ䌊��� zoom extent
				for (i = 0; i < imgArr.length; i++) {
					map.zoomToExtent(imgArr[i].extent); 
				}
			}); 
			//============= add vector =====================
			var door = new Door(this.cityCode,office,sectno, landno , wgs84x ,wgs84y ,sectName);
			addVectorToMap(door);
			loadSingleLandBySection(office,sectno); //頛匧�交㟲畾� by 畾�
			activeSection = office + "_" + sectno ; //2017-08-01 
			map.setCenter( new OpenLayers.LonLat(wgs84x,wgs84y).transform( fromProjection, toProjection)); 
			
		}else{
			alert("摰堒𧑐鞈��� ��㕑炊");
			console.log("摰堒𧑐鞈��� ��㕑炊 " , office , landno , sectno);
			return ;
		}
	});	
}
```

裡頭的getPointcity在第448行
```
function getPointCity(wgs84x, wgs84y) { 
	var _dfr = $.Deferred();
	$.ajax({
		type: "POST",
		url: "Query_json_getPointCity",
		data : {
			'wgs84x' : wgs84x,
			'wgs84y' : wgs84y
		},        			
		error: function(xhr, ajaxOptions, thrownError) {
			showSendMsg("頛匧�仿��𢒰憭望��:"+ xhr.status +":" + thrownError);
		},
		beforeSend:function(){
		},
		success: function(data) {
			var cityCode = data['cityCode'] ;
			activeCity =convertCityCode(cityCode);  //霈𦠜凒 activeCity
			var cityCodeObj = {'cityCode' : cityCode} ; 
			_dfr.resolve(cityCodeObj);
		}
	});			
	return _dfr.promise();
}

**Comment by Yukaii** [comment]
> 第一次在專案中提問，不知道這樣的提問方式是否洽當？

@Loooffy OK 的

---

我發現地籍查詢是從前端進行 POST request，我以手機版為例 (http://easymap.land.moi.gov.tw/P02/Index#coordId)，打開 Chrome Devtools 網路分頁，經緯分別輸入：`121.490255`, `25.106992`，送出：

![Screen Shot 2019-09-21 at 5 15 48 PM](https://user-images.githubusercontent.com/4230968/65371180-799ac480-dc93-11e9-8468-ee9e41ba4b53.png)

![Screen Shot 2019-09-21 at 5 01 47 PM](https://user-images.githubusercontent.com/4230968/65371045-21af8e00-dc92-11e9-953a-af51dde3b341.png)

發現有三個比較相關的 Request

- `Query_json_getPointCity`: 拿經緯所在的城市代碼
- `setToken`：拿取 POST 需要的驗證資訊
- `Door_json_getDoorInfoByXY`: 用城市代碼 + 驗證資訊 + 經緯度去拿地號資訊
    ```json
	{
	  "Id": 0.0,
	  "towncode": "A15",
	  "sectno": "0845",
	  "sectName": "富安段一小段",
	  "office": "AE",
	  "landno": "104",
	  "mergeSameDoorCount": 0,
	  "nsort": 0.0
	}
	```

可以先從這裡驗證是否能夠這樣實作

[easymap.land.moi.gov.tw.har.zip](https://github.com/yoyo930021/Disfactory/files/3638511/easymap.land.moi.gov.tw.har.zip)

**Comment by Loooffy** [comment]
![image](https://user-images.githubusercontent.com/7054287/65382062-3b9fae00-dd30-11e9-82f6-c79287eff093.png)

我用python的requests簡單送這組post出去{'city':'A','coordX':'121.552679','coordY':'25.061614','struts.token.name':'token','token':'3YVN48HZ7XU2DFZ5K2TT46ABHIHWPQYU'}

得到錯誤
![image](https://user-images.githubusercontent.com/7054287/65382094-946f4680-dd30-11e9-8779-31025c6cac7b.png)

有人懂JSP嗎，目前還在找要怎麼送request，還有cookie、token這些的關聯

**Comment by pm5** [comment]
可以唷。
