### ISSUE TITLE
document table:「輸出docx」出現502

### ISSUE THREAD

**Issue by deeper747** [Disfactory/Disfactory#503]
**Describe the bug**
目前在document table無法「輸出docx」，會出現「Bad Gateway 502」的圖樣

**To Reproduce**
1. 勾選110004 ~ 110041的document
2. 選擇「輸出成docx」的action
3. 點「Go 」

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: chrome 
 - Version: 88.0.4324.150

**Additional context**
已測試跳過沒有townname、cet_staff的document，依舊無法輸出

**Comment by deeper747** [comment]
發現一次勾選少於15則公文就可以輸出了！

**Comment by Swind** [comment]
嗯嗯，那我猜有可能是因為 timeout 了，可能因為產生文件太久（因為需要去下載圖片），我看一下怎麼延長 timeout 時間 ～

**Comment by stegben** [comment]
產生文件要不要丟給 django-Q 來做？

**Comment by Swind** [comment]
可是這樣當那個 action 按下去之後，我要 response 什麼給他呢 ? 
或者是要另外提供一個下載網址給使用者讓他可以去某個地方下載文件?

**Comment by peii052** [comment]
現已改用javascript輸出公文
