### ISSUE TITLE
沒有跑出townname

### ISSUE THREAD

**Issue by peii052** [Disfactory/Disfactory#519]
**Describe the bug**
"factorys"的table，使用者回報的案件中"townname"消失

**To Reproduce**
1. Go to 'api>factorys'
2. search display number' 54323'
3. See error

**Expected behavior**
案件中出現完整townname

**Screenshots**

**Desktop (please complete the following information):**
<img width="960" alt="螢幕截圖 2021-03-24 21 05 03" src="https://user-images.githubusercontent.com/81308197/112315065-b1e5ed80-8ce4-11eb-8927-201b4552e04b.png">

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LittleWhiteYA** [comment]
```
{'Id': 0.0, 'towncode': 'O01', 'sectno': '0131', 'sectName': '隆恩段', 'office': 'OA', 'landno': '1213', 'mergeSameDoorCount': 0, 'nsort': 0.0, 'townname': ''}
```

這邊遇到的問題是說 O01 這個 towncode 是沒有存在 https://github.com/Disfactory/Disfactory/tree/master/backend/towninfo 裡面任何的檔案

**Comment by deeper747** [comment]
factory54282也沒抓到
<img width="1087" alt="截圖 2021-03-24 下午9 32 05" src="https://user-images.githubusercontent.com/60970217/112318795-633a5280-8ce8-11eb-820b-6406e302ec8e.png">
