### ISSUE TITLE
factory table 新屬性：factory_status

### ISSUE THREAD

**Issue by deeper747** [Disfactory/Disfactory#527]
**Is your feature request related to a problem? Please describe.**
- 多人協作需要知道「不檢舉」原因
- 計算「疑似新增數量」時，可以扣掉確定為「既有」的數量

**Describe the solution you'd like**
新增一個factory status的屬性，並有以下選項
- 既有低污染
- 既有高污染
- 新增建工廠
- 新增建非工廠
- 興建中
- 既有廠房新廠商

**Describe alternatives you've considered**
在factory單一頁面也有follow up的自由填寫欄位

**Additional context**
可以把現在的cet report status整個拿掉，改成這個

**Comment by aelcenganda** [comment]
我會希望不同屬性欄位可以分開，例如既有/新增建和低污染/高污染。

或是要像是之前 `gov_status` 為自由加 tag。

**Comment by deeper747** [comment]
同意
我現在想到一個分類方式，但希望保留複選的可能，因為有時可能在「新增」中會特別想拉出「興建中」來標明經發單位尚未有權責，需要特別修改公文，或是後續追蹤要注意。

- 廠房
   - 尚未判定（default）
   - 既有
   - 新增
   - 興建中
   - 難以判定
- 廠商
   - 尚未判定（default）
   - 低污染
   - 高污染
   - 其他用途
   - 新廠商寄居
   - 難以判定

**Comment by aelcenganda** [comment]
把英文欄位取名取好給小白喔

**Comment by deeper747** [comment]
- aaaaaa
  - bbbb

**Comment by peii052** [comment]
分類方式修正：

- 廠房（building_status）
  -  尚未判定（default）
  - 既有
  - 新增
  - 興建中
  - 難以判定

- 使用狀況（usage_status）
  - 尚未判定（default）
  - 低污染
  - 高污染
  - 其他用途
  - 新廠商寄居
  - 難以判定
  - **倉儲**

**Comment by deeper747** [comment]
分類方式修正：

- 廠房（building_status）
 - 既有
 - 新增
 - 興建中
 - 難以判定

- 使用狀況（usage_status）
  - 低污染業別
  - 高污染業別
  - 其他用途
  - 難以判定

- 需注意類別（highlight）
 - 新廠商寄居
 - 倉儲

**Comment by deeper747** [comment]
剛剛嘗試在production上面改動factory status後儲存，會跳Server Error (500)

**步驟**
- 點開任意factory
- 把Building status改成「新增」
- 按下save
- 出現500

在staging也一樣
抱歉之前沒有測試好> <

**Comment by deeper747** [comment]
因應未來未來空拍圖比對結果要匯入，最近審查也發現這個類別，
想要在highlight_category新增一個「擴建」標籤，變成這樣：
- 需注意類別（highlight_category）
  - 新廠商寄居
  - 倉儲
  - 擴建
