### ISSUE TITLE
在dev.disfactory.tw上新增照片，會出現在正式版的django後台上

### ISSUE THREAD

**Issue by deeper747** [Disfactory/Disfactory#557]
**Describe the bug**
示範在dev.disfactory.tw上傳照片給志工看，結果發現照片都是跑到正式版的django上XD

**Expected behavior**
讓上傳照片出現在staging的django上

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome

**Comment by Yukaii** [comment]
Duplicate of https://github.com/Disfactory/frontend/issues/109
