### ISSUE TITLE
打imgur自動化

### ISSUE THREAD

**Issue by deeper747** [Disfactory/Disfactory#576]
**Is your feature request related to a problem? Please describe.**
每半年打一次使用者上傳imgur的圖片可以自動化

**Describe the solution you'd like**
寫一段script，
- 從db中抓出所有imgur網址
- 跟IU寫好的接在一起
- 備份到server

頻率選項
- 每天100筆
- 每個月一次全部
- 每三個月一次全部

**Describe alternatives you've considered**
每次都手動打

**Comment by tai271828** [comment]
I am glad to help and need a senior supervises me if possible : )

**Comment by tai271828** [comment]
有人知道上一次打是什麼時候嗎?

**Comment by tai271828** [comment]
**Missing Info That we may Aligned in the Regular Meetup**
- [ ] The type instance running the cron job (or similar). Is it a Ubuntu (which distributioin?), docker/lxc image (image flavor?), or something else (e.g. airflow DAG)? As the developer I want to know the environment so I know how I implement the script.
- [ ] How could we extract the data of the db? Is the db running in the same instance which runs the cron-job? Is the db running n a docker image?
- [ ] 跟IU寫好的接在一起 <-- does this mean by `imgur-keeper`?
- [ ] The backup policy is unclear to me. For example, which resource we have? How do people access the resource?

**Comment by tai271828** [comment]
跟小白對過一次，這個 issue 由他執行。我處理一次性手動的 https://github.com/Disfactory/imgur-keeper/issues/1

**Comment by tai271828** [comment]
for what it's worth: 亂爬了一下， 六個月的限制「可能」已經取消了 (as of 2015)[1][2]，不過我一直沒有爬到官方的說明「無論是否是匿名，上傳圖片是不是也是都會永久保存」

[1] https://www.quora.com/Imgur-How-long-are-the-images-stored-before-being-purged/answer/David-Bain
[2] https://webapps.stackexchange.com/questions/75993/how-long-does-imgur-store-uploaded-images?newreg=2c75f4e97967495786bbbb771e573663

```
Imgur used to delete uploaded images that haven't got any views in six months: https://wayback.archive.org/web/20141212172016/http://imgur.com/faq#long
It seems that since February 2015, when Imgur Pro service was discontinued, Imgur has preserved all images: https://blog.imgur.com/2015/02/09/imgur-pro-for-everyone/
```
