### ISSUE TITLE
Openlayer API Playground

### ISSUE THREAD

**Issue by yoyo930021** [Disfactory/Disfactory#6]

**Comment by Yukaii** [comment]
- 動態加 features: https://openlayers.org/en/latest/examples/draw-and-modify-features.html
- 在 feature 按鍵事件時顯示額外的資訊: https://openlayers.org/en/latest/examples/icon.html
- 對 marker icon 的圖片做 pixel 級操作: https://openlayers.org/en/latest/examples/icon-negative.html (應該是不會用到)

**Comment by Yukaii** [comment]
- https://openlayers.org/en/latest/apidoc/module-ol_interaction_Draw-Draw.html
- https://openlayers.org/en/latest/apidoc/module-ol_events_condition.html#~Condition

**Comment by Yukaii** [comment]
Remove feature

- https://gis.stackexchange.com/questions/251770/how-can-i-clear-a-vector-layer-features-in-openlayers-4

**Comment by Yukaii** [comment]
VectorSource 可以動態增加 Feature，以 MVP 來說應該只管增加就好

- https://openlayers.org/en/latest/apidoc/module-ol_source_Vector-VectorSource.html#addFeature
- https://openlayers.org/en/latest/apidoc/module-ol_source_Vector-VectorSource.html#removeFeature

**Comment by Yukaii** [comment]
```js
map.getLayers().array_[3].getSource().getFeatures()[1].getId()
```

**Comment by Yukaii** [comment]
Zoom scale distance 之類的

https://gis.stackexchange.com/questions/242424/how-to-get-map-units-to-find-current-scale-in-openlayers
