### ISSUE TITLE
網頁標題優化

### ISSUE THREAD

**Issue by wutingy** [Disfactory/Disfactory#601]
因為 GA4  會靠網頁標題分，不知道能不能修改每一頁的標題？

## 標題
`${title}="大家來找廠 | 動手指拆工廠 | "`
https://spot.disfactory.tw/#/ `${title}首頁`
https://spot.disfactory.tw/#/tutorial `${title}教學`
https://spot.disfactory.tw/#/game `${title}辨識`
https://spot.disfactory.tw/#/ending `${title}結束`

## event note（這個已經設定好了）
開始辨識 - `start-game`
確認送出 - `send-answer`
再玩一輪 - `play-again`
分享 - `share`
看關於專案 - `view-about`

**Comment by wutingy** [comment]
這邊附上 GA4 預設的 view 截圖
![Screen Shot 2022-04-28 at 11 24 39 AM](https://user-images.githubusercontent.com/8353239/165670258-5478811f-e863-4306-b28e-d536c6e10772.png)

**Comment by dyfu95** [comment]
> 能不能修改每一頁的標題？
可以做，但需要額外載套件來實作。
不知道GA4可不可以根據url不同區分呢？

**Comment by wutingy** [comment]
@dyfu95 可以依照 url 只是他預設的 dashboard 是用標題，點進去可以看詳細
