### ISSUE TITLE
公文後台在個案更改經緯度無法連動到land code

### ISSUE THREAD

**Issue by peii052** [Disfactory/Disfactory#631]
**Describe the bug**
在公文後台更改個案的經緯度時，照理來說townname、sectname、sectcode、landcode會連動更改，但這個功能失效ㄌ

**To Reproduce**
1. Go to '公文後台 -> factory'
2. Click on '任一個案'
3. Scroll down to 'DETAIL'
    更改經緯度，就會發現townname、sectname、sectcode、landcode並沒有連動
<img width="901" alt="螢幕擷取畫面 2023-04-12 174338" src="https://user-images.githubusercontent.com/81308197/231420312-34124973-5296-41c7-addf-1b2c1b83bb41.png">

**Expected behavior**
我要他連動~~~~~~~~~~~~~~~~~~~~~~

**Desktop (please complete the following information):**
 - OS: [e.g. windows 10]
 - Browser [brave]

**Comment by Swind** [comment]
之前因為網站有擋國外 IP，所以有使用 Tor 來嘗試取得台灣的 IP 來取得地段號。
但是今天測試，看起來 Tor 的 IP 也都被擋了
