### ISSUE TITLE
無法產生公文

### ISSUE THREAD

**Issue by peii052** [Disfactory/Disfactory#643]
**Describe the bug**
勾選案件後，下拉選單選擇「產生公文」並送出，會出現server error 500的畫面

**To Reproduce**
1. Go to '[staging.](https://staging.disfactory.tw/admin/api/document/)'
2. Click on 'Factorys' category
3. 選取案件
4. 在action選單中勾選「產生公文」並送出
5. See error

**Expected behavior**
可以順利執行「產生公文」，不會出現錯誤訊息頁面

**Screenshots**

**Desktop (please complete the following information):**
 - OS: win10
 - Browser brave

**Comment by Yukaii** [comment]
@Swind 會先多部署一台機器

**Comment by Yukaii** [comment]
addressed in #646
