### ISSUE TITLE
使用教學頁面

### ISSUE THREAD

**Issue by Oriyar** [Disfactory/Disfactory#66]
把網頁內容、選單文字確定

- 安全須知P.1
- 安全須知P.2
- 安全須知P.3
- 安全須知P.4
- 使用教學
- 聯絡我們
- 關於舉報系統

把文字內容做成 HackMD 給前端

**Comment by Oriyar** [comment]
@Yukaii @yoyo930021 文字在這裡唷
https://hackmd.io/13m0i5N3RNGunOsp8oYkKA

**Comment by Oriyar** [comment]
安全須知的配圖

https://www.dropbox.com/sh/ig5bfzum27a7wb0/AABDGV4MSpUmL4QkuW1zcCYJa?dl=0&fbclid=IwAR0FdiFHfvIcfP9csqnVMw4b6I29i5UOB8quLsPLiwjTKaRsGTdV2NyhLW8

**Comment by Yukaii** [comment]
還差使用教學的圖文

**Comment by aelcenganda** [comment]
@Oriyar 還差使用教學的圖文喔！

**Comment by Oriyar** [comment]
我更新了～ 蟹蟹yukai!

**Comment by Oriyar** [comment]
使用教學圖片的部分山爪正在處理～ @Yukaii 敲他何時交貨～
