### ISSUE TITLE
Create Factory 太久了

### ISSUE THREAD

**Issue by stegben** [Disfactory/Disfactory#79]
現在 middle2 上 create 一次要三秒，可能是要地號那裡跑太久

**Comment by Yukaii** [comment]
用貓貓解決一切問題

https://loading.io/

**Comment by stegben** [comment]
https://www.youtube.com/watch?v=wZZ7oFKsKzY

**Comment by aelcenganda** [comment]
我把這個 issue 調成 high priority，因為使用者實在不確定到底送出了沒，會跳走。不需要改後端，希望可以加上 loading 圖案，或是一行字「小幫手正在回報......」

**Comment by aelcenganda** [comment]
我願意付錢買貓貓 loading
https://loading.io/spinner/bluecat/-cat-longcat-spin-blue-rotate

或是用免費的：
https://loading.io/spinner/rolling/-bar-circle-curve-round-rotate
