### ISSUE TITLE
Usability testing plan

### ISSUE THREAD

**Issue by Oriyar** [Disfactory/Disfactory#83]
To do:

- [x] Set up Google Spreadsheet to record usability test results – identifying key ruser stories and expected outcomes.
- [x] Test 3 persons on meetup
- [ ] Test 5 persons on the ground

**Comment by aelcenganda** [comment]
@Oriyar 再拜託下週要拉上可以去農地現場做使用者測試的人。

**Comment by aelcenganda** [comment]
測試的 Google Spreadsheet 在此：
https://docs.google.com/spreadsheets/d/1LnJ3ux6G3yOtjsPtMxcTAd0o3_90EW_XbiUa9cM2JXE/edit#gid=0

需要權限的人請 request

**Comment by aelcenganda** [comment]
實地測試後的 user feedback 在這個 Slack thread
https://app.slack.com/client/T02G2SXKM/CNA60GZJM/thread/CNA60GZJM-1577256575.036900
