### ISSUE TITLE
更多可更新（建議）的欄位

### ISSUE THREAD

**Issue by Yukaii** [Disfactory/Disfactory#98]
https://github.com/Disfactory/Disfactory/blob/96807e9c9b4cfa091178ca3853cd842c061f12a3/backend/api/views/factories_u.py#L45-L52

**Comment by Yukaii** [comment]
- 工廠名稱
- 工廠圖片
- 工廠類型
- 其它資訊（已經有了）

**Comment by stegben** [comment]
名稱和類型其實可以更新了，可以參考這個 test case:
https://github.com/Disfactory/Disfactory/blob/96807e9c9b4cfa091178ca3853cd842c061f12a3/backend/api/views/tests/test_factories_u.py#L49-L55

**Comment by stegben** [comment]
圖片的話要 call 另外一個 API:
https://github.com/Disfactory/Disfactory/blob/master/backend/api/views/tests/test_factory_image_c.py#L32-L37

**Comment by Yukaii** [comment]
還需要 nickcname
